console.log("Trivia DB Module Evaluating...");

export const library = {
    themes: {
        "standard": { name: "Standard Jeopardy", categories: ["Before & After", "4-Letter Words", "Science", "English", "Barroom Physics"] },
        "history": { name: "The History Vault", categories: ["US History", "Wars", "America", "Ancient Greece", "The 1980s"] },
        "pop": { name: "Pop Culture Blender", categories: ["Memes", "Reality TV", "Viral Moments", "Current Events", "Famous People"] },
        "music": { name: "Music Masters", categories: ["Rock n' Roll Riots", "Lyrics about Liquor", "80s One-Hit Wonders", "Rap", "Haus (House Music)"] },
        "booze": { name: "Beers, Bars & Booze", categories: ["Potent Potables", "Pub Grub", "Beer Science", "Alcohol Trivia", "Famous Bars"] }
    },
    pool: {
        "Potent Potables": [
            { question: "This Japanese rice wine is often served warm.", answer: "What is Sake?" },
            { question: "This cocktail consists of vodka, ginger beer, and lime juice.", answer: "What is a Moscow Mule?" },
            { question: "The primary ingredient in a Screwdriver.", answer: "What is Vodka?" },
            { question: "This Scottish region is famous for its peat-smoked whiskies.", answer: "What is Islay?" },
            { question: "A 'perfect' Manhattan uses equal parts of sweet and dry types of this wine.", answer: "What is Vermouth?" },
            { question: "This spirit is made from the agave plant.", answer: "What is Tequila?" },
            { question: "This drink is made with gin and vermouth and garnished with an olive.", answer: "What is a Martini?" },
            { question: "A Mojito typically contains this herb.", answer: "What is Mint?" },
            { question: "This Irish stout is known for its creamy head.", answer: "What is Guinness?" },
            { question: "This clear spirit is often associated with Russia.", answer: "What is Vodka?" },
            { question: "A Margarita is typically served in a glass rimmed with...", answer: "What is Salt?" },
            { question: "This liqueur is flavored with orange.", answer: "What is Cointreau (or Triple Sec)?" },
            { question: "A White Russian contains vodka, coffee liqueur, and...", answer: "What is Cream?" },
            { question: "This wine is known for its bubbles.", answer: "What is Champagne?" },
            { question: "A Bloody Mary is made with this juice.", answer: "What is Tomato Juice?" },
            { question: "This cocktail is made with gin, lemon juice, sugar, and club soda.", answer: "What is a Tom Collins?" },
            { question: "A Daiquiri is made with this spirit.", answer: "What is Rum?" },
            { question: "This Italian liqueur is almond-flavored.", answer: "What is Amaretto?" },
            { question: "A Piña Colada contains pineapple juice, rum, and...", answer: "What is Coconut Cream?" },
            { question: "This drink is a mix of beer and lemonade.", answer: "What is a Shandy?" }
        ],
        "Before & After": [
            { question: "A high-ranking card in a deck joins forces with a common garden tool.", answer: "What is Ace of Spades?" },
            { question: "A breakfast pastry circle meets the capital of India.", answer: "What is New Delhi Bagel?" },
            { question: "A famous secret agent number combines with a convenience store chain.", answer: "What is 007-Eleven?" },
            { question: "A classic board game of property trading merges with a contagious disease.", answer: "What is Monopoly-nucleosis?" },
            { question: "The King of Pop meets a delicious pepperoni pie.", answer: "What is Michael Jackson's Pizza?" },
            { question: "A large flightless bird meets a popular ride-sharing app.", answer: "What is Ostrich Uber?" },
            { question: "The 16th US President meets a luxury car brand.", answer: "What is Abraham Lincoln Continental?" },
            { question: "A famous wizard boy meets a pottery maker.", answer: "What is Harry Potter Barn?" },
            { question: "The Star Wars jedi master meets a dairy product.", answer: "What is Yoda Yogurt?" },
            { question: "A web-slinging superhero meets a heavy metal band.", answer: "What is Spider-Man Metallica?" },
            { question: "The author of 'Dracula' meets a famous cookie.", answer: "What is Bram Stoker's Oreo?" },
            { question: "A tropical fruit meets a tech company logo.", answer: "What is Mango Apple?" },
            { question: "The first man on the moon meets a strong arm muscle.", answer: "What is Neil Armstrong Bicep?" },
            { question: "A famous painter meets a type of pasta.", answer: "What is Pablo Picasso Penne?" },
            { question: "The capital of France meets a Hilton heiress.", answer: "What is Paris Hilton?" },
            { question: "A grilled sandwich meets a cheesy snack.", answer: "What is Cheese Burger King?" },
            { question: "A boxing legend meets a cartoon alligator.", answer: "What is Muhammad Ali Gator?" },
            { question: "A fast car meets a fictional spy.", answer: "What is Ferrari Bond?" },
            { question: "A long yellow fruit meets a republic.", answer: "What is Banana Republic?" },
            { question: "A country singer meets a Brooks brother.", answer: "What is Garth Brooks Brothers?" }
        ],
        "4-Letter Words": [
            { question: "Not far.", answer: "What is Near?" },
            { question: "To emit a loud, deep cry like a lion.", answer: "What is Roar?" },
            { question: "A large body of saltwater.", answer: "What is Seas?" },
            { question: "To move rapidly on foot.", answer: "What is Race?" },
            { question: "The highest point of something.", answer: "What is Apex?" },
            { question: "A type of tree with acorns.", answer: "What is Oaks?" },
            { question: "A very small amount.", answer: "What is Iota?" },
            { question: "To look at closely.", answer: "What is Gaze?" },
            { question: "A strong wind.", answer: "What is Gale?" },
            { question: "The opposite of love.", answer: "What is Hate?" },
            { question: "A classic card game.", answer: "What is Uno?" },
            { question: "To exist.", answer: "What is Be?" },
            { question: "A mythical giant.", answer: "What is Ogre?" },
            { question: "To assist.", answer: "What is Help?" },
            { question: "A part of a poem.", answer: "What is Line?" },
            { question: "A sour citrus fruit.", answer: "What is Lime?" },
            { question: "To walk with a limp.", answer: "What is Hobble? (Wait, that is 6 letters. Correction: Limp)" },
            { question: "A heavenly body.", answer: "What is Star?" },
            { question: "To pull along.", answer: "What is Drag?" },
            { question: "A type of fuel.", answer: "What is Coal?" }
        ],
        "Science": [
            { question: "The chemical symbol for Gold.", answer: "What is Au?" },
            { question: "The hardest natural substance on Earth.", answer: "What is Diamond?" },
            { question: "This planet is known as the Red Planet.", answer: "What is Mars?" },
            { question: "The process by which plants convert sunlight into energy.", answer: "What is Photosynthesis?" },
            { question: "He developed the theory of relativity.", answer: "Who is Albert Einstein?" },
            { question: "The center of an atom.", answer: "What is The Nucleus?" },
            { question: "The speed of light.", answer: "What is 299,792,458 m/s?" },
            { question: "The most abundant gas in the atmosphere.", answer: "What is Nitrogen?" },
            { question: "The study of fossils.", answer: "What is Paleontology?" },
            { question: "The force that keeps us on the ground.", answer: "What is Gravity?" },
            { question: "The powerhouse of the cell.", answer: "What is The Mitochondria?" },
            { question: "The chemical formula for water.", answer: "What is H2O?" },
            { question: "This planet has rings.", answer: "What is Saturn?" },
            { question: "The study of the mind.", answer: "What is Psychology?" },
            { question: "This element is needed for breathing.", answer: "What is Oxygen?" },
            { question: "The process of a caterpillar turning into a butterfly.", answer: "What is Metamorphosis?" },
            { question: "The smallest unit of life.", answer: "What is A Cell?" },
            { question: "The chemical symbol for Iron.", answer: "What is Fe?" },
            { question: "The Big Bang theory explains this.", answer: "What is The Origin of the Universe?" },
            { question: "This scientist discovered penicillin.", answer: "Who is Alexander Fleming?" }
        ],
        "US History": [
            { question: "The first President of the United States.", answer: "Who is George Washington?" },
            { question: "The year the Declaration of Independence was signed.", answer: "What is 1776?" },
            { question: "This war was fought between the North and South states.", answer: "What is The Civil War?" },
            { question: "He gave the 'I Have a Dream' speech.", answer: "Who is Martin Luther King Jr.?" },
            { question: "The amendment that gave women the right to vote.", answer: "What is The 19th Amendment?" },
            { question: "The 16th President of the United States.", answer: "Who is Abraham Lincoln?" },
            { question: "The ship the Pilgrims sailed on.", answer: "What is The Mayflower?" },
            { question: "The date of the Pearl Harbor attack.", answer: "What is December 7, 1941?" },
            { question: "He wrote the Declaration of Independence.", answer: "Who is Thomas Jefferson?" },
            { question: "The purchase of Alaska was known as this.", answer: "What is Seward's Folly?" },
            { question: "The first man on the moon.", answer: "Who is Neil Armstrong?" },
            { question: "The war fought against the British for independence.", answer: "What is The Revolutionary War?" },
            { question: "The amendment that abolished slavery.", answer: "What is The 13th Amendment?" },
            { question: "The year Columbus arrived in the Americas.", answer: "What is 1492?" },
            { question: "The 44th President of the United States.", answer: "Who is Barack Obama?" },
            { question: "The scandal that forced Nixon to resign.", answer: "What is Watergate?" },
            { question: "The document that starts 'We the People'.", answer: "What is The Constitution?" },
            { question: "The period of prohibition of alcohol.", answer: "What is Prohibition?" },
            { question: "The battle that was the turning point of the Civil War.", answer: "What is Gettysburg?" },
            { question: "He is on the $100 bill.", answer: "Who is Benjamin Franklin?" }
        ],
        "Wars": [
            { question: "The 'War to End All Wars'.", answer: "What is World War I?" },
            { question: "The longest war in US history (until Afghanistan).", answer: "What is The Vietnam War?" },
            { question: "The battle that ended Napoleon's rule.", answer: "What is Waterloo?" },
            { question: "The 100 Years War was fought between these two countries.", answer: "Who are England and France?" },
            { question: "The treaty that ended the Revolutionary War.", answer: "What is The Treaty of Paris?" },
            { question: "The war that involved the Axis and Allied powers.", answer: "What is World War II?" },
            { question: "The war between North and South Korea.", answer: "What is The Korean War?" },
            { question: "The war known as Desert Storm.", answer: "What is The Gulf War?" },
            { question: "The war between the US and Mexico in the 1840s.", answer: "What is The Mexican-American War?" },
            { question: "The war that lasted from 1939 to 1945.", answer: "What is World War II?" },
            { question: "The Cold War was primarily between the US and...", answer: "Who is The Soviet Union?" },
            { question: "The war that started in 2003.", answer: "What is The Iraq War?" },
            { question: "The battle of Normandy is also known as...", answer: "What is D-Day?" },
            { question: "The war that featured trench warfare.", answer: "What is World War I?" },
            { question: "The Spanish Civil War took place in this decade.", answer: "What is The 1930s?" },
            { question: "The war of 1812 was fought between the US and...", answer: "Who is Great Britain?" },
            { question: "The Peloponnesian War was fought between Athens and...", answer: "What is Sparta?" },
            { question: "The war that ended with the Treaty of Versailles.", answer: "What is World War I?" },
            { question: "The Six-Day War took place in this region.", answer: "What is The Middle East?" },
            { question: "The Franco-Prussian War led to the unification of...", answer: "What is Germany?" }
        ],
        "America": [
            { question: "The capital of the United States.", answer: "What is Washington D.C.?" },
            { question: "The number of stars on the US flag.", answer: "What is 50?" },
            { question: "The purchase that doubled the size of the US in 1803.", answer: "What is The Louisiana Purchase?" },
            { question: "The only President to serve more than two terms.", answer: "Who is Franklin D. Roosevelt?" },
            { question: "The site of the first English settlement in America.", answer: "What is Jamestown?" },
            { question: "The largest state by area.", answer: "What is Alaska?" },
            { question: "The smallest state by area.", answer: "What is Rhode Island?" },
            { question: "The river that borders Mexico and the US.", answer: "What is The Rio Grande?" },
            { question: "The mountain range in the eastern US.", answer: "What are The Appalachians?" },
            { question: "The longest river in the US.", answer: "What is The Missouri River?" },
            { question: "The state known as the Sunshine State.", answer: "What is Florida?" },
            { question: "The city known as the Big Apple.", answer: "What is New York City?" },
            { question: "The national bird of the US.", answer: "What is The Bald Eagle?" },
            { question: "The anthem of the United States.", answer: "What is The Star-Spangled Banner?" },
            { question: "The year the US entered WWII.", answer: "What is 1941?" },
            { question: "The state where the Grand Canyon is located.", answer: "What is Arizona?" },
            { question: "The capital of California.", answer: "What is Sacramento?" },
            { question: "The declaration of independence was signed in this city.", answer: "What is Philadelphia?" },
            { question: "The first state to ratify the constitution.", answer: "What is Delaware?" },
            { question: "The mountain range in the western US.", answer: "What are The Rockies?" }
        ],
        "Ancient Greece": [
            { question: "The King of the Greek Gods.", answer: "Who is Zeus?" },
            { question: "This city-state was known for its military discipline.", answer: "What is Sparta?" },
            { question: "He wrote The Iliad and The Odyssey.", answer: "Who is Homer?" },
            { question: "The temple dedicated to Athena on the Acropolis.", answer: "What is The Parthenon?" },
            { question: "The philosopher sentenced to death by hemlock.", answer: "Who is Socrates?" },
            { question: "The goddess of love and beauty.", answer: "Who is Aphrodite?" },
            { question: "The god of the sea.", answer: "Who is Poseidon?" },
            { question: "The hero who completed 12 labors.", answer: "Who is Hercules?" },
            { question: "The messenger of the gods.", answer: "Who is Hermes?" },
            { question: "The goddess of wisdom.", answer: "Who is Athena?" },
            { question: "The mythical creature with snakes for hair.", answer: "Who is Medusa?" },
            { question: "The city-state known for democracy.", answer: "What is Athens?" },
            { question: "The war between the Greeks and Trojans.", answer: "What is The Trojan War?" },
            { question: "The wooden horse used to enter Troy.", answer: "What is The Trojan Horse?" },
            { question: "The home of the gods.", answer: "What is Mount Olympus?" },
            { question: "The god of the underworld.", answer: "Who is Hades?" },
            { question: "The philosopher who was a student of Socrates.", answer: "Who is Plato?" },
            { question: "The philosopher who was a student of Plato.", answer: "Who is Aristotle?" },
            { question: "The games held every four years in Olympia.", answer: "What are The Olympics?" },
            { question: "The sea monster with many heads.", answer: "What is The Hydra?" }
        ],
        "The 1980s": [
            { question: "This wall came down in 1989.", answer: "What is The Berlin Wall?" },
            { question: "The US President for most of the decade.", answer: "Who is Ronald Reagan?" },
            { question: "The space shuttle that tragically exploded in 1986.", answer: "What is Challenger?" },
            { question: "This musical format overtook vinyl sales in 1988.", answer: "What are Cassette Tapes?" },
            { question: "The event held in Philadelphia and London to fight famine in Ethiopia.", answer: "What is Live Aid?" },
            { question: "The movie featuring E.T.", answer: "What is E.T. the Extra-Terrestrial?" },
            { question: "The singer known as the Material Girl.", answer: "Who is Madonna?" },
            { question: "The video game featuring a yellow circle eating dots.", answer: "What is Pac-Man?" },
            { question: "The Rubik's Cube became a craze in this decade.", answer: "What are The 80s?" },
            { question: "The movie where 'Nobody puts Baby in a corner'.", answer: "What is Dirty Dancing?" },
            { question: "The TV show set in a bar where everyone knows your name.", answer: "What is Cheers?" },
            { question: "The singer of 'Thriller'.", answer: "Who is Michael Jackson?" },
            { question: "The console released by Nintendo in 1985 (US).", answer: "What is The NES?" },
            { question: "The movie involving a DeLorean time machine.", answer: "What is Back to the Future?" },
            { question: "The band that sang 'Don't Stop Believin''.", answer: "Who are Journey?" },
            { question: "The royal wedding of 1981 was between Charles and...", answer: "Who is Diana?" },
            { question: "The disaster at a nuclear power plant in 1986.", answer: "What is Chernobyl?" },
            { question: "The term for young urban professionals.", answer: "What are Yuppies?" },
            { question: "The movie with the line 'I'll be back'.", answer: "What is The Terminator?" },
            { question: "The song 'Eye of the Tiger' is from this movie.", answer: "What is Rocky III?" }
        ],
        "English": [
            { question: "26 letters make up this set.", answer: "What is The Alphabet?" },
            { question: "A word that names a person, place, or thing.", answer: "What is a Noun?" },
            { question: "The past tense of 'run'.", answer: "What is Ran?" },
            { question: "A punctuation mark used to indicate a pause stronger than a comma.", answer: "What is a Semicolon?" },
            { question: "The study of the origin of words.", answer: "What is Etymology?" },
            { question: "A word that describes a noun.", answer: "What is an Adjective?" },
            { question: "A word that describes a verb.", answer: "What is an Adverb?" },
            { question: "Two words that sound the same but have different meanings.", answer: "What are Homophones?" },
            { question: "A short story with a moral, often featuring animals.", answer: "What is a Fable?" },
            { question: "The person telling the story.", answer: "Who is The Narrator?" },
            { question: "A comparison using 'like' or 'as'.", answer: "What is a Simile?" },
            { question: "A comparison not using 'like' or 'as'.", answer: "What is a Metaphor?" },
            { question: "Giving human qualities to non-human things.", answer: "What is Personification?" },
            { question: "The main character in a story.", answer: "Who is The Protagonist?" },
            { question: "The opponent of the main character.", answer: "Who is The Antagonist?" },
            { question: "A 14-line poem.", answer: "What is a Sonnet?" },
            { question: "The repetition of initial consonant sounds.", answer: "What is Alliteration?" },
            { question: "The use of words that imitate sounds.", answer: "What is Onomatopoeia?" },
            { question: "A statement that seems contradictory but may be true.", answer: "What is a Paradox?" },
            { question: "The feeling created in the reader by a literary work.", answer: "What is Mood?" }
        ],
        "Memes": [
            { question: "This grumpy animal became an internet sensation.", answer: "Who is Grumpy Cat?" },
            { question: "This distracted boyfriend ignored his girlfriend for another woman in a stock photo.", answer: "What is The Distracted Boyfriend?" },
            { question: "'One does not simply walk into' this place.", answer: "What is Mordor?" },
            { question: "This green puppet sipping tea implies 'But that's none of my business'.", answer: "Who is Kermit the Frog?" },
            { question: "The dress color debate: Blue and Black or White and...", answer: "What is Gold?" },
            { question: "The meme featuring a Shiba Inu dog.", answer: "What is Doge?" },
            { question: "The woman yelling at a cat at a dinner table.", answer: "What is Woman Yelling at a Cat?" },
            { question: "The meme where a man taps his head to show intelligence.", answer: "What is Roll Safe?" },
            { question: "The meme of a mocked Spongebob.", answer: "What is Mocking Spongebob?" },
            { question: "The meme 'Is this a pigeon?'.", answer: "What is The Distracted Boyfriend? (Wait, correction: Is This A Pigeon meme)" },
            { question: "The frog riding a unicycle.", answer: "Who is Dat Boi?" },
            { question: "The challenge involving staying still like a mannequin.", answer: "What is The Mannequin Challenge?" },
            { question: "The meme 'Change my mind'.", answer: "Who is Steven Crowder?" },
            { question: "The meme 'Hide the Pain Harold'.", answer: "Who is Harold?" },
            { question: "The meme 'Success Kid'.", answer: "Who is Sam Griner?" },
            { question: "The meme 'Disaster Girl'.", answer: "Who is Zoe Roth?" },
            { question: "The meme 'Bad Luck Brian'.", answer: "Who is Kyle Craven?" },
            { question: "The meme 'First World Problems'.", answer: "What is First World Problems?" },
            { question: "The meme 'Overly Attached Girlfriend'.", answer: "Who is Laina Morris?" },
            { question: "The meme 'Ermahgerd'.", answer: "What is Goosebumps?" }
        ],
        "Reality TV": [
            { question: "This family has kept up with audiences for over a decade.", answer: "Who are The Kardashians?" },
            { question: "Contestants try to outwit, outplay, and outlast on this show.", answer: "What is Survivor?" },
            { question: "Gordon Ramsay yells at aspiring chefs in this kitchen.", answer: "What is Hell's Kitchen?" },
            { question: "This show features drag queens competing for the crown.", answer: "What is RuPaul's Drag Race?" },
            { question: "The shore house in this MTV show was located in Seaside Heights.", answer: "What is Jersey Shore?" },
            { question: "The show where strangers get married at first sight.", answer: "What is Married at First Sight?" },
            { question: "The show where finding love is an island adventure.", answer: "What is Love Island?" },
            { question: "The show featuring the 'Real Housewives'.", answer: "What is The Real Housewives?" },
            { question: "The show where entrepreneurs pitch to investors.", answer: "What is Shark Tank?" },
            { question: "The show where singers compete with turning chairs.", answer: "What is The Voice?" },
            { question: "The show where celebrities dance with professionals.", answer: "What is Dancing with the Stars?" },
            { question: "The show about a pawn shop in Las Vegas.", answer: "What is Pawn Stars?" },
            { question: "The show about storage locker auctions.", answer: "What is Storage Wars?" },
            { question: "The show about catching catfish online.", answer: "What is Catfish?" },
            { question: "The show about 19 kids and counting.", answer: "What is 19 Kids and Counting?" },
            { question: "The show about extreme home makeovers.", answer: "What is Extreme Makeover: Home Edition?" },
            { question: "The show where people race around the world.", answer: "What is The Amazing Race?" },
            { question: "The show about intense dance moms.", answer: "What is Dance Moms?" },
            { question: "The show involving bachelors and roses.", answer: "What is The Bachelor?" },
            { question: "The show following deckhands on a yacht.", answer: "What is Below Deck?" }
        ],
        "Viral Moments": [
            { question: "This challenge involved pouring cold water on your head.", answer: "What is The Ice Bucket Challenge?" },
            { question: "This Korean song broke YouTube view records in 2012.", answer: "What is Gangnam Style?" },
            { question: "The kid who just wanted to grow up to be a 'Berry' (Vine).", answer: "What is 'I love you b*tch'?" },
            { question: "This gorilla's death sparked a massive internet movement.", answer: "Who is Harambe?" },
            { question: "The hawk tuah girl became famous for explaining an intimate act.", answer: "Who is Hailey Welch?" },
            { question: "The dress that broke the internet.", answer: "What is The Dress?" },
            { question: "The song 'Friday' was sung by...", answer: "Who is Rebecca Black?" },
            { question: "The video 'Charlie bit me'.", answer: "What is Charlie Bit My Finger?" },
            { question: "The challenge involving eating a Tide Pod.", answer: "What is The Tide Pod Challenge?" },
            { question: "The song 'What Does the Fox Say?'.", answer: "What is Ylvis?" },
            { question: "The challenge involving flipping a bottle.", answer: "What is The Bottle Flip Challenge?" },
            { question: "The kid who yodeled in Walmart.", answer: "Who is Mason Ramsey?" },
            { question: "The woman who wore a Chewbacca mask.", answer: "Who is Chewbacca Mom?" },
            { question: "The challenge to perform the 'In My Feelings' dance.", answer: "What is The Kiki Challenge?" },
            { question: "The audio illusion 'Yanny or Laurel'.", answer: "What is Yanny or Laurel?" },
            { question: "The challenge involving a cinnamon spoon.", answer: "What is The Cinnamon Challenge?" },
            { question: "The time everyone raided Area 51.", answer: "What is The Area 51 Raid?" },
            { question: "The potato that flew around the room.", answer: "What is A Potato?" },
            { question: "The cat that plays the keyboard.", answer: "Who is Keyboard Cat?" },
            { question: "The double rainbow guy.", answer: "Who is Double Rainbow Guy?" }
        ],
        "Current Events": [
            { question: "The platform formerly known as Twitter.", answer: "What is X?" },
            { question: "This AI chatbot started a revolution in 2022.", answer: "What is ChatGPT?" },
            { question: "This country hosted the 2024 Summer Olympics.", answer: "What is France?" },
            { question: "The movie that famously battled 'Barbie' at the box office.", answer: "What is Oppenheimer?" },
            { question: "This crypto exchange collapsed spectacularly involving Sam Bankman-Fried.", answer: "What is FTX?" },
            { question: "The submarine that imploded visiting the Titanic.", answer: "What is The Titan?" },
            { question: "The King crowned in England in 2023.", answer: "Who is King Charles III?" },
            { question: "The tech company that released the Vision Pro.", answer: "What is Apple?" },
            { question: "The singer who dated Travis Kelce.", answer: "Who is Taylor Swift?" },
            { question: "The wildfire that devastated Maui.", answer: "What is The Lahaina Fire?" },
            { question: "The country that invaded Ukraine in 2022.", answer: "What is Russia?" },
            { question: "The app that ByteDance owns.", answer: "What is TikTok?" },
            { question: "The huge sphere venue in Las Vegas.", answer: "What is The Sphere?" },
            { question: "The actor who played Ken in Barbie.", answer: "Who is Ryan Gosling?" },
            { question: "The trial involving Johnny Depp and...", answer: "Who is Amber Heard?" },
            { question: "The winner of the 2022 FIFA World Cup.", answer: "What is Argentina?" },
            { question: "The streaming service that cracks down on password sharing.", answer: "What is Netflix?" },
            { question: "The strikes that halted Hollywood.", answer: "What are The SAG-AFTRA/WGA Strikes?" },
            { question: "The variant of COVID-19 named after a Greek letter O.", answer: "What is Omicron?" },
            { question: "The planet showing signs of potential life (Phosphine).", answer: "What is Venus?" }
        ],
        "Famous People": [
            { question: "The founder of Tesla and SpaceX.", answer: "Who is Elon Musk?" },
            { question: "This singer is known for her 'Eras' tour.", answer: "Who is Taylor Swift?" },
            { question: "The actor who played Iron Man.", answer: "Who is Robert Downey Jr.?" },
            { question: "This British Prince released a memoir titled 'Spare'.", answer: "Who is Prince Harry?" },
            { question: "He slapped Chris Rock at the Oscars.", answer: "Who is Will Smith?" },
            { question: "The Queen of Pop.", answer: "Who is Madonna?" },
            { question: "The King of Rock and Roll.", answer: "Who is Elvis Presley?" },
            { question: "The first black President of the US.", answer: "Who is Barack Obama?" },
            { question: "The founder of Microsoft.", answer: "Who is Bill Gates?" },
            { question: "The founder of Amazon.", answer: "Who is Jeff Bezos?" },
            { question: "The author of Harry Potter.", answer: "Who is J.K. Rowling?" },
            { question: "The host of The Oprah Winfrey Show.", answer: "Who is Oprah Winfrey?" },
            { question: "The actor known as 'The Rock'.", answer: "Who is Dwayne Johnson?" },
            { question: "The singer of 'Rolling in the Deep'.", answer: "Who is Adele?" },
            { question: "The painter of the Mona Lisa.", answer: "Who is Leonardo da Vinci?" },
            { question: "The scientist who formulated gravity.", answer: "Who is Isaac Newton?" },
            { question: "The Civil Rights leader.", answer: "Who is Martin Luther King Jr.?" },
            { question: "The first woman to fly across the Atlantic.", answer: "Who is Amelia Earhart?" },
            { question: "The boxer known as 'The Greatest'.", answer: "Who is Muhammad Ali?" },
            { question: "The creator of Mickey Mouse.", answer: "Who is Walt Disney?" }
        ],
        "Rock n' Roll Riots": [
            { question: "This band sang 'I Wanna Be Sedated'.", answer: "Who are The Ramones?" },
            { question: "He smashed his guitar on stage, defining The Who.", answer: "Who is Pete Townshend?" },
            { question: "The lead singer of The Rolling Stones.", answer: "Who is Mick Jagger?" },
            { question: "This festival in 1999 ended in fires and riots.", answer: "What is Woodstock '99?" },
            { question: "The band known for the song 'Smells Like Teen Spirit'.", answer: "Who are Nirvana?" },
            { question: "The band that released 'Dark Side of the Moon'.", answer: "Who are Pink Floyd?" },
            { question: "The guitarist who played 'Eruption'.", answer: "Who is Eddie Van Halen?" },
            { question: "The drummer for Led Zeppelin.", answer: "Who is John Bonham?" },
            { question: "The band known as the Fab Four.", answer: "Who are The Beatles?" },
            { question: "The singer known as the Lizard King.", answer: "Who is Jim Morrison?" },
            { question: "The band that sings 'Bohemian Rhapsody'.", answer: "Who are Queen?" },
            { question: "The singer of 'Born to Run'.", answer: "Who is Bruce Springsteen?" },
            { question: "The band featuring Axl Rose and Slash.", answer: "Who are Guns N' Roses?" },
            { question: "The bassist for the Red Hot Chili Peppers.", answer: "Who is Flea?" },
            { question: "The band that wrote 'Stairway to Heaven'.", answer: "Who are Led Zeppelin?" },
            { question: "The singer known for painting his face (KISS).", answer: "Who is Gene Simmons?" },
            { question: "The band that sang 'Hotel California'.", answer: "Who are The Eagles?" },
            { question: "The artist known as Ziggy Stardust.", answer: "Who is David Bowie?" },
            { question: "The band called 'The bad boys from Boston'.", answer: "Who are Aerosmith?" },
            { question: "The grunge band fronted by Chris Cornell.", answer: "Who are Soundgarden?" }
        ],
        "Lyrics about Liquor": [
            { question: "'It's five o'clock somewhere'.", answer: "Who is Alan Jackson?" },
            { question: "'Tequila makes her clothes fall off'.", answer: "Who is Joe Nichols?" },
            { question: "'Red red wine, you make me feel so fine'.", answer: "Who are UB40?" },
            { question: "'I got friends in low places, where the whiskey drowns...'.", answer: "Who is Garth Brooks?" },
            { question: "'One bourbon, one scotch, and one beer'.", answer: "Who is George Thorogood?" },
            { question: "'I love this bar'.", answer: "Who is Toby Keith?" },
            { question: "'Margaritaville'.", answer: "Who is Jimmy Buffett?" },
            { question: "'Whiskey River, take my mind'.", answer: "Who is Willie Nelson?" },
            { question: "'Piano Man' mentions 'sharing a drink they call loneliness'.", answer: "Who is Billy Joel?" },
            { question: "'Beer for my horses'.", answer: "Who are Toby Keith and Willie Nelson?" },
            { question: "'Strawberry Wine'.", answer: "Who is Deana Carter?" },
            { question: "'Tennessee Whiskey'.", answer: "Who is Chris Stapleton?" },
            { question: "'Tubthumping' (I get knocked down...).", answer: "Who are Chumbawamba?" },
            { question: "'Brass Monkey'.", answer: "Who are The Beastie Boys?" },
            { question: "'Gin and Juice'.", answer: "Who is Snoop Dogg?" },
            { question: "'Shots' feat. Lil Jon.", answer: "Who are LMFAO?" },
            { question: "'Cheers (Drink to That)'.", answer: "Who is Rihanna?" },
            { question: "'Blame It (On the Alcohol)'.", answer: "Who is Jamie Foxx?" },
            { question: "'Tipsy'.", answer: "Who is J-Kwon?" },
            { question: "'Bottoms Up'.", answer: "Who is Trey Songz?" }
        ],
        "80s One-Hit Wonders": [
            { question: "'Come on Eileen'.", answer: "Who are Dexys Midnight Runners?" },
            { question: "'Take On Me'.", answer: "Who are A-ha?" },
            { question: "'I melt with you'.", answer: "Who are Modern English?" },
            { question: "'867-5309/Jenny'.", answer: "Who are Tommy Tutone?" },
            { question: "'Turning Japanese'.", answer: "Who are The Vapors?" },
            { question: "'Tainted Love'.", answer: "Who are Soft Cell?" },
            { question: "'Relax'.", answer: "Who are Frankie Goes to Hollywood?" },
            { question: "'Whip It'.", answer: "Who are Devo?" },
            { question: "'Video Killed the Radio Star'.", answer: "Who are The Buggles?" },
            { question: "'Safety Dance'.", answer: "Who are Men Without Hats?" },
            { question: "'Too Shy'.", answer: "Who are Kajagoogoo?" },
            { question: "'Mickey'.", answer: "Who is Toni Basil?" },
            { question: "'She Blinded Me with Science'.", answer: "Who is Thomas Dolby?" },
            { question: "'99 Luftballons'.", answer: "Who is Nena?" },
            { question: "'Puttin' on the Ritz'.", answer: "Who is Taco?" },
            { question: "'Walking on Sunshine'.", answer: "Who are Katrina and the Waves?" },
            { question: "'Pass the Dutchie'.", answer: "Who are Musical Youth?" },
            { question: "'Funkytown'.", answer: "Who are Lipps Inc.?" },
            { question: "'Electric Avenue'.", answer: "Who is Eddy Grant?" },
            { question: "'My Sharona'.", answer: "Who are The Knack? (Technically 79/80)" }
        ],
        "Rap": [
            { question: "He is known as the 'Rap God'.", answer: "Who is Eminem?" },
            { question: "This Canadian rapper started on Degrassi.", answer: "Who is Drake?" },
            { question: "This group said 'Fight the Power'.", answer: "Who are Public Enemy?" },
            { question: "He released 'The Blueprint'.", answer: "Who is Jay-Z?" },
            { question: "This Kendrick Lamar album won a Pulitzer Prize.", answer: "What is DAMN.?" },
            { question: "The rapper who died in 1996.", answer: "Who is Tupac Shakur?" },
            { question: "The rapper who died in 1997.", answer: "Who is Notorious B.I.G.?" },
            { question: "The group consisting of Dr. Dre, Ice Cube, etc.", answer: "Who are N.W.A.?" },
            { question: "The rapper known for 'Gold Digger'.", answer: "Who is Kanye West?" },
            { question: "The rapper from Detroit.", answer: "Who is Eminem?" },
            { question: "The female rapper known for 'Super Bass'.", answer: "Who is Nicki Minaj?" },
            { question: "The rapper known for 'Bodak Yellow'.", answer: "Who is Cardi B?" },
            { question: "The rapper who founded Bad Boy Records.", answer: "Who is Diddy?" },
            { question: "The group known for 'C.R.E.A.M.'.", answer: "Who are Wu-Tang Clan?" },
            { question: "The rapper known for 'In Da Club'.", answer: "Who is 50 Cent?" },
            { question: "The rapper known for 'Hotline Bling'.", answer: "Who is Drake?" },
            { question: "The rapper known for 'SICKO MODE'.", answer: "Who is Travis Scott?" },
            { question: "The rapper known for 'Old Town Road'.", answer: "Who is Lil Nas X?" },
            { question: "The rapper known for 'Stan'.", answer: "Who is Eminem?" },
            { question: "The rapper known for 'Ms. Jackson'.", answer: "Who are OutKast?" }
        ],
        "Haus (House Music)": [
            { question: "This French duo wore robot helmets.", answer: "Who are Daft Punk?" },
            { question: "The city where House music originated.", answer: "What is Chicago?" },
            { question: "This DJ released 'Levels'.", answer: "Who is Avicii?" },
            { question: "They released 'One More Time'.", answer: "Who are Daft Punk?" },
            { question: "The BPM range typical for House music.", answer: "What is 115-130 BPM?" },
            { question: "The warehouse in Chicago often cited as the birthplace.", answer: "What is The Warehouse?" },
            { question: "The DJ known as the Godfather of House.", answer: "Who is Frankie Knuckles?" },
            { question: "The subgenre known for acid sounds.", answer: "What is Acid House?" },
            { question: "The island famous for house music parties.", answer: "What is Ibiza?" },
            { question: "The group known for 'Don't You Worry Child'.", answer: "Who are Swedish House Mafia?" },
            { question: "The DJ known for 'Titanium'.", answer: "Who is David Guetta?" },
            { question: "The DJ known for 'Summer'.", answer: "Who is Calvin Harris?" },
            { question: "The duo known for 'Closer'.", answer: "Who are The Chainsmokers?" },
            { question: "The DJ known for throwing cake.", answer: "Who is Steve Aoki?" },
            { question: "The electronic instrument crucial for Acid House.", answer: "What is The Roland TB-303?" },
            { question: "The festival in Belgium dedicated to electronic music.", answer: "What is Tomorrowland?" },
            { question: "The DJ known for a mouse helmet.", answer: "Who is Deadmau5?" },
            { question: "The DJ known for 'Scary Monsters and Nice Sprites'.", answer: "Who is Skrillex?" },
            { question: "The song 'Sandstorm'.", answer: "Who is Darude?" },
            { question: "The subgenre known for deeper, soulful sounds.", answer: "What is Deep House?" }
        ],
        "Pub Grub": [
            { question: "This 'fishy' dish paired with chips is a staple of British pub culture.", answer: "What is Fish and Chips?" },
            { question: "Invented in Buffalo, NY, these spicy poultry pieces are a bar favorite.", answer: "What are Buffalo Wings?" },
            { question: "This purely Canadian dish features fries, cheese curds, and gravy.", answer: "What is Poutine?" },
            { question: "Typically pickled and served in massive jars on bars.", answer: "What are Pickled Eggs?" },
            { question: "This 'Ploughman's' meal was promoted to sell more of this dairy product.", answer: "What is Cheese?" },
            { question: "A scotch egg is a hard-boiled egg wrapped in...", answer: "What is Sausage Meat?" },
            { question: "Bangers and Mash refers to sausages and...", answer: "What are Mashed Potatoes?" },
            { question: "A Shepherd's Pie is typically made with this meat.", answer: "What is Lamb?" },
            { question: "Toad in the Hole involves sausages cooked in...", answer: "What is Yorkshire Pudding Batter?" },
            { question: "Nachos originated in this country.", answer: "What is Mexico?" },
            { question: "Mozzarella sticks are typically served with this sauce.", answer: "What is Marinara?" },
            { question: "A slider is a small version of this.", answer: "What is A Hamburger?" },
            { question: "Fried calamari is made from this sea creature.", answer: "What is Squid?" },
            { question: "Jalapeño poppers are often filled with...", answer: "What is Cream Cheese?" },
            { question: "A pretzel is often dipped in this yellow condiment.", answer: "What is Mustard?" },
            { question: "Onion rings are onions dipped in...", answer: "What is Batter?" },
            { question: "Potato skins are often topped with bacon and...", answer: "What is Cheese?" },
            { question: "Chili cheese fries are fries topped with...", answer: "What is Chili and Cheese?" },
            { question: "A BLT stands for...", answer: "What is Bacon, Lettuce, Tomato?" },
            { question: "A Reuben sandwich contains this meat.", answer: "What is Corned Beef?" }
        ],
        "Beer Science": [
            { question: "This four-letter ingredient provides bitterness and aroma to beer.", answer: "What are Hops?" },
            { question: "This microorganism is responsible for fermentation.", answer: "What is Yeast?" },
            { question: "This scale, abbreviated IBU, measures the bitterness of beer.", answer: "What is IBU?" },
            { question: "Ales are top-fermented, while lagers are...", answer: "What is Bottom-fermented?" },
            { question: "The Reinheitsgebot is a purity law from this country.", answer: "What is Germany?" },
            { question: "Malt is typically made from this grain.", answer: "What is Barley?" },
            { question: "ABV stands for...", answer: "What is Alcohol By Volume?" },
            { question: "The dark color of stouts comes from...", answer: "What is Roasted Malt?" },
            { question: "IPA stands for...", answer: "What is India Pale Ale?" },
            { question: "The process of heating the wort is called...", answer: "What is Boiling?" },
            { question: "Specific Gravity measures the density of the beer relative to...", answer: "What is Water?" },
            { question: "The gas produced during fermentation.", answer: "What is Carbon Dioxide?" },
            { question: "A session beer is known for having low...", answer: "What is Alcohol Content?" },
            { question: "Trappist beers must be brewed by...", answer: "Who are Monks?" },
            { question: "The study of fermentation is called...", answer: "What is Zymurgy?" },
            { question: "Dry hopping involves adding hops during...", answer: "What is Fermentation/Conditioning?" },
            { question: "A growler is a container used to carry...", answer: "What is Beer?" },
            { question: "The head on a beer is also called...", answer: "What is Foam?" },
            { question: "Brewing involves mashing, laundering, boiling, and...", answer: "What is Fermenting?" },
            { question: "A cicerone is a certified expert in...", answer: "What is Beer?" }
        ],
        "Alcohol Trivia": [
            { question: "Tequila must be made from this plant.", answer: "What is Blue Agave?" },
            { question: "This clear spirit is flavored with juniper berries.", answer: "What is Gin?" },
            { question: "Which country drinks the most wine per capita?", answer: "What is The Vatican City?" },
            { question: "Mead is an alcoholic beverage made by fermenting this sweet substance.", answer: "What is Honey?" },
            { question: "What does the 'VSOP' stand for on a Cognac bottle?", answer: "What is Very Superior Old Pale?" },
            { question: "Rum is made from...", answer: "What is Sugarcane/Molasses?" },
            { question: "Vodka basically means this in Russian.", answer: "What is Little Water?" },
            { question: "Sake is made from...", answer: "What is Rice?" },
            { question: "Bourbon must be made in this country.", answer: "What is The United States?" },
            { question: "Scotch must be made in this country.", answer: "What is Scotland?" },
            { question: "Champagne must be produced in this region of France.", answer: "What is Champagne?" },
            { question: "The worm in the bottom of a bottle is actually found in...", answer: "What is Mezcal?" },
            { question: "Absinthe was banned for causing...", answer: "What is Hallucinations?" },
            { question: "Brandy is made from...", answer: "What is Grapes/Fruit?" },
            { question: "Cider is made from...", answer: "What is Apples?" },
            { question: "Soju is a popular spirit in...", answer: "What is South Korea?" },
            { question: "Baileys is an Irish...?", answer: "What is Cream Liqueur?" },
            { question: "Jägermeister contains this many herbs and spices.", answer: "What is 56?" },
            { question: "Kahlúa is a liqueur flavored with...", answer: "What is Coffee?" },
            { question: "Sambuca is flavored with...", answer: "What is Anise?" }
        ],
        "Famous Bars": [
            { question: "The bar where everybody knows your name.", answer: "What is Cheers?" },
            { question: "Quant's favorite cantina in Star Wars.", answer: "What is Mos Eisley Cantina?" },
            { question: "The pub in Shaun of the Dead.", answer: "What is The Winchester?" },
            { question: "The iconic Irish pub in 'It's Always Sunny in Philadelphia'.", answer: "What is Paddy's Pub?" },
            { question: "The bar in the Shining.", answer: "What is The Gold Room?" },
            { question: "The bar in How I Met Your Mother.", answer: "What is MacLaren's Pub?" },
            { question: "The bar in Friends (coffee shop, but iconic).", answer: "What is Central Perk?" },
            { question: "The bar in The Simpsons.", answer: "What is Moe's Tavern?" },
            { question: "The bar in Family Guy.", answer: "What is The Drunken Clam?" },
            { question: "The bar in Casablanca.", answer: "What is Rick's Café Américain?" },
            { question: "The bar in Coyote Ugly.", answer: "What is Coyote Ugly?" },
            { question: "The fictional bar in Harry Potter.", answer: "What is The Three Broomsticks?" },
            { question: "The bar in New Girl.", answer: "What is The Griffin?" },
            { question: "The bar in Grey's Anatomy.", answer: "What is Joe's Bar?" },
            { question: "The bar in The Sopranos.", answer: "What is Bada Bing!" },
            { question: "The bar in True Blood.", answer: "What is Fangtasia?" },
            { question: "The bar in Twin Peaks.", answer: "What is The Roadhouse?" },
            { question: "The bar in Goodfellas.", answer: "What is The Bamboo Lounge?" },
            { question: "The club in Scarface.", answer: "What is The Babylon Club?" },
            { question: "The bar in Indiana Jones.", answer: "What is Club Obi Wan?" }
        ],
        "Barroom Physics": [
            { question: "The force that keeps foam at the top of a beer.", answer: "What is Buoyancy?" },
            { question: "Why a Guinness bubble sinks (circulation patterns).", answer: "What is Drag?" },
            { question: "The effect that causes wine legs (tears).", answer: "What is The Marangoni Effect?" },
            { question: "Condensation forms on the outside of a cold glass because of this.", answer: "What is Dew Point?" },
            { question: "The density of alcohol relative to water (less or more).", answer: "What is Less?" },
            { question: "The shape of a liquid droplet is due to...", answer: "What is Surface Tension?" },
            { question: "Why ice floats in a drink.", answer: "What is Density (Ice is less dense)?" },
            { question: "The sound a bottle makes when you blow across it is resonance.", answer: "What is Resonance?" },
            { question: "The Coanda effect explains why liquid...?", answer: "What is Clings to the curved surface of a glass?" },
            { question: "The freezing point of alcohol is...?", answer: "What is Lower than water?" },
            { question: "Sublimation is when a solid turns directly into...", answer: "What is Gas?" },
            { question: "The Leidenfrost effect can be seen when liquid hits...", answer: "What is A hot surface?" },
            { question: "The study of fluids in motion.", answer: "What is Fluid Dynamics?" },
            { question: "Why a shaken soda explodes (nucleation sites).", answer: "What are Nucleation Sites?" },
            { question: "The reason a straw works (pressure).", answer: "What is Atmospheric Pressure?" },
            { question: "The meniscus of water in a glass curves...", answer: "What is Up?" },
            { question: "The meniscus of mercury in a glass curves...", answer: "What is Down?" },
            { question: "The speed of sound travels faster in liquids than in...", answer: "What is Gas?" },
            { question: "Refraction makes a straw look...", answer: "What is Bent?" },
            { question: "Viscosity is the measure of a fluid's...", answer: "What is Resistance to flow?" }
        ]
    }
};
