console.log("Trivia DB Module Evaluating...");

export const library = {
    themes: {
        "standard": { name: "Standard Jeopardy", categories: ["Before & After", "4-Letter Words", "Science", "English", "Barroom Physics"] },
        "history": { name: "The History Vault", categories: ["US History", "Wars", "America", "Ancient Greece", "The 1980s"] },
        "pop": { name: "Pop Culture Blender", categories: ["Blockbuster Movies", "Reality TV", "Slogans & Brands", "Current Events", "Famous People"] },
        "music": { name: "Music Masters", categories: ["Rock n' Roll Riots", "Lyrics about Liquor", "80s One-Hit Wonders", "Rap", "Haus (House Music)"] },
        "booze": { name: "Beers, Bars & Booze", categories: ["Potent Potables", "Pub Grub", "Beer Science", "Alcohol Trivia", "Famous Bars"] }
    },
    pool: {
        "Potent Potables": [
            { question: "The primary ingredient in a Screwdriver.", answer: "What is Vodka?", difficulty: 1 },
            { question: "This Japanese rice wine is often served warm.", answer: "What is Sake?", difficulty: 1 },
            { question: "A Margarita is typically served in a glass rimmed with...", answer: "What is Salt?", difficulty: 1 },
            { question: "This clear spirit is often associated with Russia.", answer: "What is Vodka?", difficulty: 1 },
            { question: "This wine is known for its bubbles.", answer: "What is Champagne?", difficulty: 2 },
            { question: "A Mojito typically contains this herb.", answer: "What is Mint?", difficulty: 2 },
            { question: "This irish stout is known for its creamy head.", answer: "What is Guinness?", difficulty: 2 },
            { question: "A Daiquiri is made with this spirit.", answer: "What is Rum?", difficulty: 2 },
            { question: "This spirit is made from the agave plant.", answer: "What is Tequila?", difficulty: 3 },
            { question: "A White Russian contains vodka, coffee liqueur, and...", answer: "What is Cream?", difficulty: 3 },
            { question: "This liqueur is flavored with orange.", answer: "What is Cointreau (or Triple Sec)?", difficulty: 3 },
            { question: "A Bloody Mary is made with this juice.", answer: "What is Tomato Juice?", difficulty: 3 },
            { question: "This cocktail consists of vodka, ginger beer, and lime juice.", answer: "What is a Moscow Mule?", difficulty: 4 },
            { question: "This drink is made with gin and vermouth and garnished with an olive.", answer: "What is a Martini?", difficulty: 4 },
            { question: "This Italian liqueur is almond-flavored.", answer: "What is Amaretto?", difficulty: 4 },
            { question: "A Piña Colada contains pineapple juice, rum, and...", answer: "What is Coconut Cream?", difficulty: 4 },
            { question: "This Scottish region is famous for its peat-smoked whiskies.", answer: "What is Islay?", difficulty: 5 },
            { question: "A 'perfect' Manhattan uses equal parts of sweet and dry types of this wine.", answer: "What is Vermouth?", difficulty: 5 },
            { question: "This cocktail is made with gin, lemon juice, sugar, and club soda.", answer: "What is a Tom Collins?", difficulty: 5 },
            { question: "This drink is a mix of beer and lemonade.", answer: "What is a Shandy?", difficulty: 5 }
        ],
        "Before & After": [
            { question: "The King of Pop meets a delicious pepperoni pie.", answer: "What is Michael Jackson's Pizza?", difficulty: 1 },
            { question: "A long yellow fruit meets a republic.", answer: "What is Banana Republic?", difficulty: 1 },
            { question: "A grilled sandwich meets a cheesy snack.", answer: "What is Cheese Burger King?", difficulty: 1 },
            { question: "The Star Wars jedi master meets a dairy product.", answer: "What is Yoda Yogurt?", difficulty: 1 },
            { question: "A large flightless bird meets a popular ride-sharing app.", answer: "What is Ostrich Uber?", difficulty: 2 },
            { question: "A tropical fruit meets a tech company logo.", answer: "What is Mango Apple?", difficulty: 2 },
            { question: "A boxing legend meets a cartoon alligator.", answer: "What is Muhammad Ali Gator?", difficulty: 2 },
            { question: "The famous wizard boy meets a pottery maker.", answer: "What is Harry Potter Barn?", difficulty: 2 },
            { question: "A famous secret agent number combines with a convenience store chain.", answer: "What is 007-Eleven?", difficulty: 3 },
            { question: "A high-ranking card in a deck joins forces with a common garden tool.", answer: "What is Ace of Spades?", difficulty: 3 },
            { question: "The first man on the moon meets a strong arm muscle.", answer: "What is Neil Armstrong Bicep?", difficulty: 3 },
            { question: "The capital of France meets a Hilton heiress.", answer: "What is Paris Hilton?", difficulty: 3 },
            { question: "A breakfast pastry circle meets the capital of India.", answer: "What is New Delhi Bagel?", difficulty: 4 },
            { question: "A fast car meets a fictional spy.", answer: "What is Ferrari Bond?", difficulty: 4 },
            { question: "A web-slinging superhero meets a heavy metal band.", answer: "What is Spider-Man Metallica?", difficulty: 4 },
            { question: "The author of 'Dracula' meets a famous cookie.", answer: "What is Bram Stoker's Oreo?", difficulty: 4 },
            { question: "A classic board game of property trading merges with a contagious disease.", answer: "What is Monopoly-nucleosis?", difficulty: 5 },
            { question: "The 16th US President meets a luxury car brand.", answer: "What is Abraham Lincoln Continental?", difficulty: 5 },
            { question: "A famous painter meets a type of pasta.", answer: "What is Pablo Picasso Penne?", difficulty: 5 },
            { question: "A country singer meets a Brooks brother.", answer: "What is Garth Brooks Brothers?", difficulty: 5 }
        ],
        "4-Letter Words": [
            { question: "Not far.", answer: "What is Near?", difficulty: 1 },
            { question: "The opposite of love.", answer: "What is Hate?", difficulty: 1 },
            { question: "To assist.", answer: "What is Help?", difficulty: 1 },
            { question: "A very small amount.", answer: "What is Iota?", difficulty: 5 },
            { question: "To emit a loud, deep cry like a lion.", answer: "What is Roar?", difficulty: 2 },
            { question: "A large body of saltwater.", answer: "What is Seas?", difficulty: 2 },
            { question: "To move rapidly on foot.", answer: "What is Race?", difficulty: 2 },
            { question: "To look at closely.", answer: "What is Gaze?", difficulty: 3 },
            { question: "A part of a poem.", answer: "What is Line?", difficulty: 3 },
            { question: "A sour citrus fruit.", answer: "What is Lime?", difficulty: 1 },
            { question: "The highest point of something.", answer: "What is Apex?", difficulty: 4 },
            { question: "A type of tree with acorns.", answer: "What is Oaks?", difficulty: 2 },
            { question: "A strong wind.", answer: "What is Gale?", difficulty: 4 },
            { question: "To exist.", answer: "What is Be?", difficulty: 3 },
            { question: "A classic card game.", answer: "What is Uno?", difficulty: 1 },
            { question: "A mythical giant.", answer: "What is Ogre?", difficulty: 4 },
            { question: "To walk with a limp.", answer: "What is Limp?", difficulty: 2 },
            { question: "A heavenly body.", answer: "What is Star?", difficulty: 2 },
            { question: "To pull along.", answer: "What is Drag?", difficulty: 3 },
            { question: "A type of fuel.", answer: "What is Coal?", difficulty: 3 }
        ],
        "Science": [
            { question: "The chemical formula for water.", answer: "What is H2O?", difficulty: 1 },
            { question: "This planet has rings.", answer: "What is Saturn?", difficulty: 1 },
            { question: "The center of an atom.", answer: "What is The Nucleus?", difficulty: 2 },
            { question: "The force that keeps us on the ground.", answer: "What is Gravity?", difficulty: 1 },
            { question: "The study of fossils.", answer: "What is Paleontology?", difficulty: 3 },
            { question: "The chemical symbol for Gold.", answer: "What is Au?", difficulty: 3 },
            { question: "The process by which plants convert sunlight into energy.", answer: "What is Photosynthesis?", difficulty: 3 },
            { question: "The hardest natural substance on Earth.", answer: "What is Diamond?", difficulty: 2 },
            { question: "He developed the theory of relativity.", answer: "Who is Albert Einstein?", difficulty: 4 },
            { question: "The speed of light.", answer: "What is 299,792,458 m/s? (approx 300k km/s)", difficulty: 5 },
            { question: "The most abundant gas in the atmosphere.", answer: "What is Nitrogen?", difficulty: 4 },
            { question: "The powerhouse of the cell.", answer: "What is The Mitochondria?", difficulty: 2 },
            { question: "The study of the mind.", answer: "What is Psychology?", difficulty: 2 },
            { question: "This element is needed for breathing.", answer: "What is Oxygen?", difficulty: 1 },
            { question: "The process of a caterpillar turning into a butterfly.", answer: "What is Metamorphosis?", difficulty: 2 },
            { question: "The smallest unit of life.", answer: "What is A Cell?", difficulty: 3 },
            { question: "The chemical symbol for Iron.", answer: "What is Fe?", difficulty: 4 },
            { question: "The Big Bang theory explains this.", answer: "What is The Origin of the Universe?", difficulty: 3 },
            { question: "This scientist discovered penicillin.", answer: "Who is Alexander Fleming?", difficulty: 5 },
            { question: "The red planet.", answer: "What is Mars?", difficulty: 1 }
        ],
        // ... (Repeating pattern for brevity in this tool call, but full file will be written)
        "US History": [
            { question: "The first President of the United States.", answer: "Who is George Washington?", difficulty: 1 },
            { question: "The 16th President of the United States.", answer: "Who is Abraham Lincoln?", difficulty: 1 },
            { question: "The year the Declaration of Independence was signed.", answer: "What is 1776?", difficulty: 2 },
            { question: "The ship the Pilgrims sailed on.", answer: "What is The Mayflower?", difficulty: 2 },
            { question: "The first man on the moon.", answer: "Who is Neil Armstrong?", difficulty: 2 },
            { question: "He gave the 'I Have a Dream' speech.", answer: "Who is Martin Luther King Jr.?", difficulty: 1 },
            { question: "This war was fought between the North and South states.", answer: "What is The Civil War?", difficulty: 1 },
            { question: "The amendment that abolished slavery.", answer: "What is The 13th Amendment?", difficulty: 3 },
            { question: "The year Columbus arrived in the Americas.", answer: "What is 1492?", difficulty: 2 },
            { question: "The 44th President of the United States.", answer: "Who is Barack Obama?", difficulty: 1 },
            { question: "The amendment that gave women the right to vote.", answer: "What is The 19th Amendment?", difficulty: 4 },
            { question: "The date of the Pearl Harbor attack.", answer: "What is December 7, 1941?", difficulty: 4 },
            { question: "He wrote the Declaration of Independence.", answer: "Who is Thomas Jefferson?", difficulty: 3 },
            { question: "The purchase of Alaska was known as this.", answer: "What is Seward's Folly?", difficulty: 5 },
            { question: "The war fought against the British for independence.", answer: "What is The Revolutionary War?", difficulty: 2 },
            { question: "The scandal that forced Nixon to resign.", answer: "What is Watergate?", difficulty: 3 },
            { question: "The document that starts 'We the People'.", answer: "What is The Constitution?", difficulty: 3 },
            { question: "The period of prohibition of alcohol.", answer: "What is Prohibition?", difficulty: 3 },
            { question: "The battle that was the turning point of the Civil War.", answer: "What is Gettysburg?", difficulty: 4 },
            { question: "He is on the $100 bill.", answer: "Who is Benjamin Franklin?", difficulty: 5 }
        ],
        "Wars": [
            { question: "The 'War to End All Wars'.", answer: "What is World War I?", difficulty: 2 },
            { question: "The longest war in US history (until Afghanistan).", answer: "What is The Vietnam War?", difficulty: 3 },
            { question: "The battle that ended Napoleon's rule.", answer: "What is Waterloo?", difficulty: 4 },
            { question: "The 100 Years War was fought between these two countries.", answer: "Who are England and France?", difficulty: 5 },
            { question: "The treaty that ended the Revolutionary War.", answer: "What is The Treaty of Paris?", difficulty: 5 },
            { question: "The war that involved the Axis and Allied powers.", answer: "What is World War II?", difficulty: 1 },
            { question: "The war between North and South Korea.", answer: "What is The Korean War?", difficulty: 2 },
            { question: "The war known as Desert Storm.", answer: "What is The Gulf War?", difficulty: 3 },
            { question: "The war between the US and Mexico in the 1840s.", answer: "What is The Mexican-American War?", difficulty: 4 },
            { question: "The war that lasted from 1939 to 1945.", answer: "What is World War II?", difficulty: 2 },
            { question: "The Cold War was primarily between the US and...", answer: "Who is The Soviet Union?", difficulty: 2 },
            { question: "The war that started in 2003.", answer: "What is The Iraq War?", difficulty: 2 },
            { question: "The battle of Normandy is also known as...", answer: "What is D-Day?", difficulty: 3 },
            { question: "The war that featured trench warfare.", answer: "What is World War I?", difficulty: 3 },
            { question: "The Spanish Civil War took place in this decade.", answer: "What is The 1930s?", difficulty: 5 },
            { question: "The war of 1812 was fought between the US and...", answer: "Who is Great Britain?", difficulty: 4 },
            { question: "The Peloponnesian War was fought between Athens and...", answer: "What is Sparta?", difficulty: 5 },
            { question: "The war that ended with the Treaty of Versailles.", answer: "What is World War I?", difficulty: 4 },
            { question: "The Six-Day War took place in this region.", answer: "What is The Middle East?", difficulty: 4 },
            { question: "The Franco-Prussian War led to the unification of...", answer: "What is Germany?", difficulty: 5 }
        ],
        "America": [
            { question: "The capital of the United States.", answer: "What is Washington D.C.?", difficulty: 1 },
            { question: "The number of stars on the US flag.", answer: "What is 50?", difficulty: 1 },
            { question: "The purchase that doubled the size of the US in 1803.", answer: "What is The Louisiana Purchase?", difficulty: 4 },
            { question: "The only President to serve more than two terms.", answer: "Who is Franklin D. Roosevelt?", difficulty: 4 },
            { question: "The site of the first English settlement in America.", answer: "What is Jamestown?", difficulty: 3 },
            { question: "The largest state by area.", answer: "What is Alaska?", difficulty: 2 },
            { question: "The smallest state by area.", answer: "What is Rhode Island?", difficulty: 2 },
            { question: "The river that borders Mexico and the US.", answer: "What is The Rio Grande?", difficulty: 3 },
            { question: "The mountain range in the eastern US.", answer: "What are The Appalachians?", difficulty: 3 },
            { question: "The longest river in the US.", answer: "What is The Missouri River?", difficulty: 4 },
            { question: "The state known as the Sunshine State.", answer: "What is Florida?", difficulty: 1 },
            { question: "The city known as the Big Apple.", answer: "What is New York City?", difficulty: 1 },
            { question: "The national bird of the US.", answer: "What is The Bald Eagle?", difficulty: 1 },
            { question: "The anthem of the United States.", answer: "What is The Star-Spangled Banner?", difficulty: 1 },
            { question: "The year the US entered WWII.", answer: "What is 1941?", difficulty: 3 },
            { question: "The state where the Grand Canyon is located.", answer: "What is Arizona?", difficulty: 2 },
            { question: "The capital of California.", answer: "What is Sacramento?", difficulty: 5 },
            { question: "The declaration of independence was signed in this city.", answer: "What is Philadelphia?", difficulty: 3 },
            { question: "The first state to ratify the constitution.", answer: "What is Delaware?", difficulty: 5 },
            { question: "The mountain range in the western US.", answer: "What are The Rockies?", difficulty: 2 }
        ],
        "Ancient Greece": [
            { question: "The King of the Greek Gods.", answer: "Who is Zeus?", difficulty: 1 },
            { question: "This city-state was known for its military discipline.", answer: "What is Sparta?", difficulty: 2 },
            { question: "He wrote The Iliad and The Odyssey.", answer: "Who is Homer?", difficulty: 3 },
            { question: "The temple dedicated to Athena on the Acropolis.", answer: "What is The Parthenon?", difficulty: 4 },
            { question: "The philosopher sentenced to death by hemlock.", answer: "Who is Socrates?", difficulty: 4 },
            { question: "The goddess of love and beauty.", answer: "Who is Aphrodite?", difficulty: 2 },
            { question: "The god of the sea.", answer: "Who is Poseidon?", difficulty: 2 },
            { question: "The hero who completed 12 labors.", answer: "Who is Hercules?", difficulty: 1 },
            { question: "The messenger of the gods.", answer: "Who is Hermes?", difficulty: 3 },
            { question: "The goddess of wisdom.", answer: "Who is Athena?", difficulty: 2 },
            { question: "The mythical creature with snakes for hair.", answer: "Who is Medusa?", difficulty: 2 },
            { question: "The city-state known for democracy.", answer: "What is Athens?", difficulty: 2 },
            { question: "The war between the Greeks and Trojans.", answer: "What is The Trojan War?", difficulty: 2 },
            { question: "The wooden horse used to enter Troy.", answer: "What is The Trojan Horse?", difficulty: 1 },
            { question: "The home of the gods.", answer: "What is Mount Olympus?", difficulty: 1 },
            { question: "The god of the underworld.", answer: "Who is Hades?", difficulty: 2 },
            { question: "The philosopher who was a student of Socrates.", answer: "Who is Plato?", difficulty: 5 },
            { question: "The philosopher who was a student of Plato.", answer: "Who is Aristotle?", difficulty: 5 },
            { question: "The games held every four years in Olympia.", answer: "What are The Olympics?", difficulty: 3 },
            { question: "The sea monster with many heads.", answer: "What is The Hydra?", difficulty: 4 }
        ],
        "The 1980s": [
            { question: "This wall came down in 1989.", answer: "What is The Berlin Wall?", difficulty: 2 },
            { question: "The US President for most of the decade.", answer: "Who is Ronald Reagan?", difficulty: 2 },
            { question: "The space shuttle that tragically exploded in 1986.", answer: "What is Challenger?", difficulty: 3 },
            { question: "This musical format overtook vinyl sales in 1988.", answer: "What are Cassette Tapes?", difficulty: 4 },
            { question: "The event held in Philadelphia and London to fight famine in Ethiopia.", answer: "What is Live Aid?", difficulty: 5 },
            { question: "The movie featuring E.T.", answer: "What is E.T. the Extra-Terrestrial?", difficulty: 1 },
            { question: "The singer known as the Material Girl.", answer: "Who is Madonna?", difficulty: 1 },
            { question: "The video game featuring a yellow circle eating dots.", answer: "What is Pac-Man?", difficulty: 1 },
            { question: "The Rubik's Cube became a craze in this decade.", answer: "What are The 80s? (Rubik's Cube)", difficulty: 2 },
            { question: "The movie where 'Nobody puts Baby in a corner'.", answer: "What is Dirty Dancing?", difficulty: 3 },
            { question: "The TV show set in a bar where everyone knows your name.", answer: "What is Cheers?", difficulty: 2 },
            { question: "The singer of 'Thriller'.", answer: "Who is Michael Jackson?", difficulty: 1 },
            { question: "The console released by Nintendo in 1985 (US).", answer: "What is The NES?", difficulty: 3 },
            { question: "The movie involving a DeLorean time machine.", answer: "What is Back to the Future?", difficulty: 1 },
            { question: "The band that sang 'Don't Stop Believin''.", answer: "Who are Journey?", difficulty: 2 },
            { question: "The royal wedding of 1981 was between Charles and...", answer: "Who is Diana?", difficulty: 2 },
            { question: "The disaster at a nuclear power plant in 1986.", answer: "What is Chernobyl?", difficulty: 3 },
            { question: "The term for young urban professionals.", answer: "What are Yuppies?", difficulty: 4 },
            { question: "The movie with the line 'I'll be back'.", answer: "What is The Terminator?", difficulty: 1 },
            { question: "The song 'Eye of the Tiger' is from this movie.", answer: "What is Rocky III?", difficulty: 4 }
        ],
        "English": [
            { question: "26 letters make up this set.", answer: "What is The Alphabet?", difficulty: 1 },
            { question: "A word that names a person, place, or thing.", answer: "What is a Noun?", difficulty: 1 },
            { question: "The past tense of 'run'.", answer: "What is Ran?", difficulty: 1 },
            { question: "A punctuation mark used to indicate a pause stronger than a comma.", answer: "What is a Semicolon?", difficulty: 3 },
            { question: "The study of the origin of words.", answer: "What is Etymology?", difficulty: 5 },
            { question: "A word that describes a noun.", answer: "What is an Adjective?", difficulty: 2 },
            { question: "A word that describes a verb.", answer: "What is an Adverb?", difficulty: 2 },
            { question: "Two words that sound the same but have different meanings.", answer: "What are Homophones?", difficulty: 3 },
            { question: "A short story with a moral, often featuring animals.", answer: "What is a Fable?", difficulty: 3 },
            { question: "The person telling the story.", answer: "Who is The Narrator?", difficulty: 2 },
            { question: "A comparison using 'like' or 'as'.", answer: "What is a Simile?", difficulty: 2 },
            { question: "A comparison not using 'like' or 'as'.", answer: "What is a Metaphor?", difficulty: 3 },
            { question: "Giving human qualities to non-human things.", answer: "What is Personification?", difficulty: 4 },
            { question: "The main character in a story.", answer: "Who is The Protagonist?", difficulty: 3 },
            { question: "The opponent of the main character.", answer: "Who is The Antagonist?", difficulty: 3 },
            { question: "A 14-line poem.", answer: "What is a Sonnet?", difficulty: 4 },
            { question: "The repetition of initial consonant sounds.", answer: "What is Alliteration?", difficulty: 4 },
            { question: "The use of words that imitate sounds.", answer: "What is Onomatopoeia?", difficulty: 5 },
            { question: "A statement that seems contradictory but may be true.", answer: "What is a Paradox?", difficulty: 5 },
            { question: "The feeling created in the reader by a literary work.", answer: "What is Mood?", difficulty: 4 }
        ],
        "Blockbuster Movies": [
            { question: "This 2009 James Cameron film is the highest-grossing movie of all time.", answer: "What is Avatar?", difficulty: 1 },
            { question: "This movie features a sinking ship and Leo DiCaprio.", answer: "What is Titanic?", difficulty: 1 },
            { question: "The first movie in the MCU (Marvel Cinematic Universe).", answer: "What is Iron Man?", difficulty: 2 },
            { question: "The dinosaur movie directed by Steven Spielberg in 1993.", answer: "What is Jurassic Park?", difficulty: 1 },
            { question: "This animated movie features a lion cub named Simba.", answer: "What is The Lion King?", difficulty: 1 },
            { question: "The movie where Heath Ledger played the Joker.", answer: "What is The Dark Knight?", difficulty: 2 },
            { question: "This movie is set on a desert planet called Arrakis.", answer: "What is Dune?", difficulty: 3 },
            { question: "The first Star Wars movie released (Episode IV).", answer: "What is A New Hope?", difficulty: 2 },
            { question: "This movie gave us the quote 'May the odds be ever in your favor'.", answer: "What is The Hunger Games?", difficulty: 2 },
            { question: "The highest grossing animated movie of all time (as of 2024).", answer: "What is Inside Out 2?", difficulty: 3 },
            { question: "Tom Cruise flies jets in this franchise.", answer: "What is Top Gun?", difficulty: 1 },
            { question: "This movie features blue people on Pandora.", answer: "What is Avatar?", difficulty: 1 },
            { question: "The movie about a doll living in a plastic world.", answer: "What is Barbie?", difficulty: 1 },
            { question: "This 1975 movie terrified people of going into the water.", answer: "What is Jaws?", difficulty: 2 },
            { question: "The Lord of the Rings movie that won 11 Oscars.", answer: "What is The Return of the King?", difficulty: 4 },
            { question: "This movie features the song 'Let It Go'.", answer: "What is Frozen?", difficulty: 1 },
            { question: "The director of Oppenheimer.", answer: "Who is Christopher Nolan?", difficulty: 3 },
            { question: "The first Avengers movie was released in this year.", answer: "What is 2012?", difficulty: 4 },
            { question: "This movie is the highest grossing R-rated film.", answer: "What is Deadpool & Wolverine (or Joker depending on date)?", difficulty: 3 },
            { question: "The name of the skyscraper in Die Hard.", answer: "What is Nakatomi Plaza?", difficulty: 5 }
        ],
        "Reality TV": [
            { question: "This family has kept up with audiences for over a decade.", answer: "Who are The Kardashians?", difficulty: 1 },
            { question: "Contestants try to outwit, outplay, and outlast on this show.", answer: "What is Survivor?", difficulty: 1 },
            { question: "Gordon Ramsay yells at aspiring chefs in this kitchen.", answer: "What is Hell's Kitchen?", difficulty: 2 },
            { question: "This show features drag queens competing for the crown.", answer: "What is RuPaul's Drag Race?", difficulty: 2 },
            { question: "The shore house in this MTV show was located in Seaside Heights.", answer: "What is Jersey Shore?", difficulty: 2 },
            { question: "The show where strangers get married at first sight.", answer: "What is Married at First Sight?", difficulty: 3 },
            { question: "The show where finding love is an island adventure.", answer: "What is Love Island?", difficulty: 3 },
            { question: "The show featuring the 'Real Housewives'.", answer: "What is The Real Housewives?", difficulty: 1 },
            { question: "The show where entrepreneurs pitch to investors.", answer: "What is Shark Tank?", difficulty: 2 },
            { question: "The show where singers compete with turning chairs.", answer: "What is The Voice?", difficulty: 2 },
            { question: "The show where celebrities dance with professionals.", answer: "What is Dancing with the Stars?", difficulty: 2 },
            { question: "The show about a pawn shop in Las Vegas.", answer: "What is Pawn Stars?", difficulty: 3 },
            { question: "The show about storage locker auctions.", answer: "What is Storage Wars?", difficulty: 3 },
            { question: "The show about catching catfish online.", answer: "What is Catfish?", difficulty: 3 },
            { question: "The show about 19 kids and counting.", answer: "What is 19 Kids and Counting?", difficulty: 4 },
            { question: "The show about extreme home makeovers.", answer: "What is Extreme Makeover: Home Edition?", difficulty: 4 },
            { question: "The show where people race around the world.", answer: "What is The Amazing Race?", difficulty: 4 },
            { question: "The show about intense dance moms.", answer: "What is Dance Moms?", difficulty: 4 },
            { question: "The show involving bachelors and roses.", answer: "What is The Bachelor?", difficulty: 1 },
            { question: "The show following deckhands on a yacht.", answer: "What is Below Deck?", difficulty: 5 }
        ],
        "Slogans & Brands": [
            { question: "'Just Do It'.", answer: "What is Nike?", difficulty: 1 },
            { question: "'I'm Lovin' It'.", answer: "What is McDonald's?", difficulty: 1 },
            { question: "'Taste the Rainbow'.", answer: "What is Skittles?", difficulty: 1 },
            { question: "'Finger Lickin' Good'.", answer: "What is KFC?", difficulty: 1 },
            { question: "'Melts in your mouth, not in your hands'.", answer: "What are M&Ms?", difficulty: 2 },
            { question: "'The Happiest Place on Earth'.", answer: "What is Disneyland?", difficulty: 1 },
            { question: "'Think Different'.", answer: "What is Apple?", difficulty: 2 },
            { question: "'Because You're Worth It'.", answer: "What is L'Oréal?", difficulty: 3 },
            { question: "'Eat Fresh'.", answer: "What is Subway?", difficulty: 1 },
            { question: "'Red Bull gives you...'", answer: "What are Wings?", difficulty: 1 },
            { question: "'The Ultimate Driving Machine'.", answer: "What is BMW?", difficulty: 3 },
            { question: "'Maybe she's born with it. Maybe it's...'", answer: "What is Maybelline?", difficulty: 2 },
            { question: "'Have a break, have a...'", answer: "What is KitKat?", difficulty: 1 },
            { question: "'Open Happiness'.", answer: "What is Coca-Cola?", difficulty: 3 },
            { question: "'America Runs on...'", answer: "What is Dunkin'?", difficulty: 2 },
            { question: "'Belong Anywhere'.", answer: "What is Airbnb?", difficulty: 4 },
            { question: "'Can you hear me now?'.", answer: "What is Verizon?", difficulty: 3 },
            { question: "'What's in your wallet?'.", answer: "What is Capital One?", difficulty: 2 },
            { question: "'Shave Time. Shave Money.'.", answer: "What is Dollar Shave Club?", difficulty: 4 },
            { question: "'Move Fast and Break Things' (Original motto).", answer: "What is Facebook?", difficulty: 5 }
        ],
        "Current Events": [
            { question: "The platform formerly known as Twitter.", answer: "What is X?", difficulty: 1 },
            { question: "This AI chatbot started a revolution in 2022.", answer: "What is ChatGPT?", difficulty: 1 },
            { question: "This country hosted the 2024 Summer Olympics.", answer: "What is France?", difficulty: 2 },
            { question: "The movie that famously battled 'Barbie' at the box office.", answer: "What is Oppenheimer?", difficulty: 2 },
            { question: "This crypto exchange collapsed spectacularly involving Sam Bankman-Fried.", answer: "What is FTX?", difficulty: 4 },
            { question: "The submarine that imploded visiting the Titanic.", answer: "What is The Titan?", difficulty: 3 },
            { question: "The King crowned in England in 2023.", answer: "Who is King Charles III?", difficulty: 2 },
            { question: "The tech company that released the Vision Pro.", answer: "What is Apple?", difficulty: 3 },
            { question: "The singer who dated Travis Kelce.", answer: "Who is Taylor Swift?", difficulty: 1 },
            { question: "The wildfire that devastated Maui.", answer: "What is The Lahaina Fire?", difficulty: 4 },
            { question: "The country that invaded Ukraine in 2022.", answer: "What is Russia?", difficulty: 1 },
            { question: "The app that ByteDance owns.", answer: "What is TikTok?", difficulty: 2 },
            { question: "The huge sphere venue in Las Vegas.", answer: "What is The Sphere?", difficulty: 2 },
            { question: "The actor who played Ken in Barbie.", answer: "Who is Ryan Gosling?", difficulty: 2 },
            { question: "The trial involving Johnny Depp and...", answer: "Who is Amber Heard?", difficulty: 2 },
            { question: "The winner of the 2022 FIFA World Cup.", answer: "What is Argentina?", difficulty: 3 },
            { question: "The streaming service that cracks down on password sharing.", answer: "What is Netflix?", difficulty: 2 },
            { question: "The strikes that halted Hollywood.", answer: "What are The SAG-AFTRA/WGA Strikes?", difficulty: 4 },
            { question: "The variant of COVID-19 named after a Greek letter O.", answer: "What is Omicron?", difficulty: 3 },
            { question: "The planet showing signs of potential life (Phosphine).", answer: "What is Venus?", difficulty: 5 }
        ],
        "Famous People": [
            { question: "The founder of Tesla and SpaceX.", answer: "Who is Elon Musk?", difficulty: 1 },
            { question: "This singer is known for her 'Eras' tour.", answer: "Who is Taylor Swift?", difficulty: 1 },
            { question: "The actor who played Iron Man.", answer: "Who is Robert Downey Jr.?", difficulty: 2 },
            { question: "This British Prince released a memoir titled 'Spare'.", answer: "Who is Prince Harry?", difficulty: 3 },
            { question: "He slapped Chris Rock at the Oscars.", answer: "Who is Will Smith?", difficulty: 2 },
            { question: "The Queen of Pop.", answer: "Who is Madonna?", difficulty: 2 },
            { question: "The King of Rock and Roll.", answer: "Who is Elvis Presley?", difficulty: 1 },
            { question: "The first black President of the US.", answer: "Who is Barack Obama?", difficulty: 1 },
            { question: "The founder of Microsoft.", answer: "Who is Bill Gates?", difficulty: 2 },
            { question: "The founder of Amazon.", answer: "Who is Jeff Bezos?", difficulty: 2 },
            { question: "The author of Harry Potter.", answer: "Who is J.K. Rowling?", difficulty: 2 },
            { question: "The host of The Oprah Winfrey Show.", answer: "Who is Oprah Winfrey?", difficulty: 1 },
            { question: "The actor known as 'The Rock'.", answer: "Who is Dwayne Johnson?", difficulty: 2 },
            { question: "The singer of 'Rolling in the Deep'.", answer: "Who is Adele?", difficulty: 3 },
            { question: "The painter of the Mona Lisa.", answer: "Who is Leonardo da Vinci?", difficulty: 3 },
            { question: "The scientist who formulated gravity.", answer: "Who is Isaac Newton?", difficulty: 4 },
            { question: "The Civil Rights leader.", answer: "Who is Martin Luther King Jr.?", difficulty: 2 },
            { question: "The first woman to fly across the Atlantic.", answer: "Who is Amelia Earhart?", difficulty: 4 },
            { question: "The boxer known as 'The Greatest'.", answer: "Who is Muhammad Ali?", difficulty: 3 },
            { question: "The creator of Mickey Mouse.", answer: "Who is Walt Disney?", difficulty: 2 }
        ],
        "Rock n' Roll Riots": [
            { question: "This band sang 'I Wanna Be Sedated'.", answer: "Who are The Ramones?", difficulty: 3 },
            { question: "He smashed his guitar on stage, defining The Who.", answer: "Who is Pete Townshend?", difficulty: 4 },
            { question: "The lead singer of The Rolling Stones.", answer: "Who is Mick Jagger?", difficulty: 1 },
            { question: "This festival in 1999 ended in fires and riots.", answer: "What is Woodstock '99?", difficulty: 3 },
            { question: "The band known for the song 'Smells Like Teen Spirit'.", answer: "Who are Nirvana?", difficulty: 1 },
            { question: "The band that released 'Dark Side of the Moon'.", answer: "Who are Pink Floyd?", difficulty: 2 },
            { question: "The guitarist who played 'Eruption'.", answer: "Who is Eddie Van Halen?", difficulty: 2 },
            { question: "The drummer for Led Zeppelin.", answer: "Who is John Bonham?", difficulty: 5 },
            { question: "The band known as the Fab Four.", answer: "Who are The Beatles?", difficulty: 1 },
            { question: "The singer known as the Lizard King.", answer: "Who is Jim Morrison?", difficulty: 4 },
            { question: "The band that sings 'Bohemian Rhapsody'.", answer: "Who are Queen?", difficulty: 1 },
            { question: "The singer of 'Born to Run'.", answer: "Who is Bruce Springsteen?", difficulty: 2 },
            { question: "The band featuring Axl Rose and Slash.", answer: "Who are Guns N' Roses?", difficulty: 2 },
            { question: "The bassist for the Red Hot Chili Peppers.", answer: "Who is Flea?", difficulty: 3 },
            { question: "The band that wrote 'Stairway to Heaven'.", answer: "Who are Led Zeppelin?", difficulty: 2 },
            { question: "The singer known for painting his face (KISS).", answer: "Who is Gene Simmons?", difficulty: 3 },
            { question: "The band that sang 'Hotel California'.", answer: "Who are The Eagles?", difficulty: 2 },
            { question: "The artist known as Ziggy Stardust.", answer: "Who is David Bowie?", difficulty: 4 },
            { question: "The band called 'The bad boys from Boston'.", answer: "Who are Aerosmith?", difficulty: 3 },
            { question: "The grunge band fronted by Chris Cornell.", answer: "Who are Soundgarden?", difficulty: 5 }
        ],
        "Lyrics about Liquor": [
            { question: "'It's five o'clock somewhere'.", answer: "Who is Alan Jackson?", difficulty: 1 },
            { question: "'Tequila makes her clothes fall off'.", answer: "Who is Joe Nichols?", difficulty: 4 },
            { question: "'Red red wine, you make me feel so fine'.", answer: "Who are UB40?", difficulty: 2 },
            { question: "'I got friends in low places, where the whiskey drowns...'.", answer: "Who is Garth Brooks?", difficulty: 1 },
            { question: "'One bourbon, one scotch, and one beer'.", answer: "Who is George Thorogood?", difficulty: 4 },
            { question: "'I love this bar'.", answer: "Who is Toby Keith?", difficulty: 3 },
            { question: "'Margaritaville'.", answer: "Who is Jimmy Buffett?", difficulty: 1 },
            { question: "'Whiskey River, take my mind'.", answer: "Who is Willie Nelson?", difficulty: 2 },
            { question: "'Piano Man' mentions 'sharing a drink they call loneliness'.", answer: "Who is Billy Joel?", difficulty: 2 },
            { question: "'Beer for my horses'.", answer: "Who are Toby Keith and Willie Nelson?", difficulty: 3 },
            { question: "'Strawberry Wine'.", answer: "Who is Deana Carter?", difficulty: 5 },
            { question: "'Tennessee Whiskey'.", answer: "Who is Chris Stapleton?", difficulty: 2 },
            { question: "'Tubthumping' (I get knocked down...).", answer: "Who are Chumbawamba?", difficulty: 3 },
            { question: "'Brass Monkey'.", answer: "Who are The Beastie Boys?", difficulty: 3 },
            { question: "'Gin and Juice'.", answer: "Who is Snoop Dogg?", difficulty: 1 },
            { question: "'Shots' feat. Lil Jon.", answer: "Who are LMFAO?", difficulty: 2 },
            { question: "'Cheers (Drink to That)'.", answer: "Who is Rihanna?", difficulty: 2 },
            { question: "'Blame It (On the Alcohol)'.", answer: "Who is Jamie Foxx?", difficulty: 3 },
            { question: "'Tipsy'.", answer: "Who is J-Kwon?", difficulty: 5 },
            { question: "'Bottoms Up'.", answer: "Who is Trey Songz?", difficulty: 5 }
        ],
        "80s One-Hit Wonders": [
            { question: "'Come on Eileen'.", answer: "Who are Dexys Midnight Runners?", difficulty: 1 },
            { question: "'Take On Me'.", answer: "Who are A-ha?", difficulty: 1 },
            { question: "'I melt with you'.", answer: "Who are Modern English?", difficulty: 3 },
            { question: "'867-5309/Jenny'.", answer: "Who are Tommy Tutone?", difficulty: 2 },
            { question: "'Turning Japanese'.", answer: "Who are The Vapors?", difficulty: 4 },
            { question: "'Tainted Love'.", answer: "Who are Soft Cell?", difficulty: 2 },
            { question: "'Relax'.", answer: "Who are Frankie Goes to Hollywood?", difficulty: 2 },
            { question: "'Whip It'.", answer: "Who are Devo?", difficulty: 2 },
            { question: "'Video Killed the Radio Star'.", answer: "Who are The Buggles?", difficulty: 3 },
            { question: "'Safety Dance'.", answer: "Who are Men Without Hats?", difficulty: 3 },
            { question: "'Too Shy'.", answer: "Who are Kajagoogoo?", difficulty: 1 },
            { question: "'Mickey'.", answer: "Who is Toni Basil?", difficulty: 4 },
            { question: "'She Blinded Me with Science'.", answer: "Who is Thomas Dolby?", difficulty: 4 },
            { question: "'99 Luftballons'.", answer: "Who is Nena?", difficulty: 2 },
            { question: "'Puttin' on the Ritz'.", answer: "Who is Taco?", difficulty: 5 },
            { question: "'Walking on Sunshine'.", answer: "Who are Katrina and the Waves?", difficulty: 2 },
            { question: "'Pass the Dutchie'.", answer: "Who are Musical Youth?", difficulty: 5 },
            { question: "'Funkytown'.", answer: "Who are Lipps Inc.?", difficulty: 3 },
            { question: "'Electric Avenue'.", answer: "Who is Eddy Grant?", difficulty: 3 },
            { question: "'My Sharona'.", answer: "Who are The Knack?", difficulty: 2 }
        ],
        "Rap": [
            { question: "He is known as the 'Rap God'.", answer: "Who is Eminem?", difficulty: 1 },
            { question: "This Canadian rapper started on Degrassi.", answer: "Who is Drake?", difficulty: 1 },
            { question: "This group said 'Fight the Power'.", answer: "Who are Public Enemy?", difficulty: 4 },
            { question: "He released 'The Blueprint'.", answer: "Who is Jay-Z?", difficulty: 2 },
            { question: "This Kendrick Lamar album won a Pulitzer Prize.", answer: "What is DAMN.?", difficulty: 5 },
            { question: "The rapper who died in 1996.", answer: "Who is Tupac Shakur?", difficulty: 2 },
            { question: "The rapper who died in 1997.", answer: "Who is Notorious B.I.G.?", difficulty: 2 },
            { question: "The group consisting of Dr. Dre, Ice Cube, etc.", answer: "Who are N.W.A.?", difficulty: 3 },
            { question: "The rapper known for 'Gold Digger'.", answer: "Who is Kanye West?", difficulty: 1 },
            { question: "The rapper from Detroit.", answer: "Who is Eminem?", difficulty: 1 },
            { question: "The female rapper known for 'Super Bass'.", answer: "Who is Nicki Minaj?", difficulty: 2 },
            { question: "The rapper known for 'Bodak Yellow'.", answer: "Who is Cardi B?", difficulty: 2 },
            { question: "The rapper who founded Bad Boy Records.", answer: "Who is Diddy?", difficulty: 3 },
            { question: "The group known for 'C.R.E.A.M.'.", answer: "Who are Wu-Tang Clan?", difficulty: 3 },
            { question: "The rapper known for 'In Da Club'.", answer: "Who is 50 Cent?", difficulty: 2 },
            { question: "The rapper known for 'Hotline Bling'.", answer: "Who is Drake?", difficulty: 1 },
            { question: "The rapper known for 'SICKO MODE'.", answer: "Who is Travis Scott?", difficulty: 3 },
            { question: "The rapper known for 'Old Town Road'.", answer: "Who is Lil Nas X?", difficulty: 2 },
            { question: "The rapper known for 'Stan'.", answer: "Who is Eminem?", difficulty: 3 },
            { question: "The rapper known for 'Ms. Jackson'.", answer: "Who are OutKast?", difficulty: 3 }
        ],
        "Haus (House Music)": [
            { question: "This French duo wore robot helmets.", answer: "Who are Daft Punk?", difficulty: 1 },
            { question: "The city where House music originated.", answer: "What is Chicago?", difficulty: 3 },
            { question: "This DJ released 'Levels'.", answer: "Who is Avicii?", difficulty: 2 },
            { question: "They released 'One More Time'.", answer: "Who are Daft Punk?", difficulty: 1 },
            { question: "The BPM range typical for House music.", answer: "What is 115-130 BPM?", difficulty: 4 },
            { question: "The warehouse in Chicago often cited as the birthplace.", answer: "What is The Warehouse?", difficulty: 5 },
            { question: "The DJ known as the Godfather of House.", answer: "Who is Frankie Knuckles?", difficulty: 5 },
            { question: "The subgenre known for acid sounds.", answer: "What is Acid House?", difficulty: 3 },
            { question: "The island famous for house music parties.", answer: "What is Ibiza?", difficulty: 2 },
            { question: "The group known for 'Don't You Worry Child'.", answer: "Who are Swedish House Mafia?", difficulty: 2 },
            { question: "The DJ known for 'Titanium'.", answer: "Who is David Guetta?", difficulty: 2 },
            { question: "The DJ known for 'Summer'.", answer: "Who is Calvin Harris?", difficulty: 2 },
            { question: "The duo known for 'Closer'.", answer: "Who are The Chainsmokers?", difficulty: 2 },
            { question: "The DJ known for throwing cake.", answer: "Who is Steve Aoki?", difficulty: 3 },
            { question: "The electronic instrument crucial for Acid House.", answer: "What is The Roland TB-303?", difficulty: 5 },
            { question: "The festival in Belgium dedicated to electronic music.", answer: "What is Tomorrowland?", difficulty: 3 },
            { question: "The DJ known for a mouse helmet.", answer: "Who is Deadmau5?", difficulty: 1 },
            { question: "The DJ known for 'Scary Monsters and Nice Sprites'.", answer: "Who is Skrillex?", difficulty: 2 },
            { question: "The song 'Sandstorm'.", answer: "Who is Darude?", difficulty: 1 },
            { question: "The subgenre known for deeper, soulful sounds.", answer: "What is Deep House?", difficulty: 4 }
        ],
        "Pub Grub": [
            { question: "This 'fishy' dish paired with chips is a staple of British pub culture.", answer: "What is Fish and Chips?", difficulty: 1 },
            { question: "Invented in Buffalo, NY, these spicy poultry pieces are a bar favorite.", answer: "What are Buffalo Wings?", difficulty: 1 },
            { question: "This purely Canadian dish features fries, cheese curds, and gravy.", answer: "What is Poutine?", difficulty: 2 },
            { question: "Typically pickled and served in massive jars on bars.", answer: "What are Pickled Eggs?", difficulty: 3 },
            { question: "This 'Ploughman's' meal was promoted to sell more of this dairy product.", answer: "What is Cheese?", difficulty: 5 },
            { question: "A scotch egg is a hard-boiled egg wrapped in...", answer: "What is Sausage Meat?", difficulty: 3 },
            { question: "Bangers and Mash refers to sausages and...", answer: "What are Mashed Potatoes?", difficulty: 2 },
            { question: "A Shepherd's Pie is typically made with this meat.", answer: "What is Lamb?", difficulty: 2 },
            { question: "Toad in the Hole involves sausages cooked in...", answer: "What is Yorkshire Pudding Batter?", difficulty: 4 },
            { question: "Nachos originated in this country.", answer: "What is Mexico?", difficulty: 1 },
            { question: "Mozzarella sticks are typically served with this sauce.", answer: "What is Marinara?", difficulty: 1 },
            { question: "A slider is a small version of this.", answer: "What is A Hamburger?", difficulty: 1 },
            { question: "Fried calamari is made from this sea creature.", answer: "What is Squid?", difficulty: 2 },
            { question: "Jalapeño poppers are often filled with...", answer: "What is Cream Cheese?", difficulty: 2 },
            { question: "A pretzel is often dipped in this yellow condiment.", answer: "What is Mustard?", difficulty: 1 },
            { question: "Onion rings are onions dipped in...", answer: "What is Batter?", difficulty: 2 },
            { question: "Potato skins are often topped with bacon and...", answer: "What is Cheese?", difficulty: 2 },
            { question: "Chili cheese fries are fries topped with...", answer: "What is Chili and Cheese?", difficulty: 1 },
            { question: "A BLT stands for...", answer: "What is Bacon, Lettuce, Tomato?", difficulty: 1 },
            { question: "A Reuben sandwich contains this meat.", answer: "What is Corned Beef?", difficulty: 3 }
        ],
        "Beer Science": [
            { question: "This four-letter ingredient provides bitterness and aroma to beer.", answer: "What are Hops?", difficulty: 1 },
            { question: "This microorganism is responsible for fermentation.", answer: "What is Yeast?", difficulty: 2 },
            { question: "This scale, abbreviated IBU, measures the bitterness of beer.", answer: "What is IBU?", difficulty: 3 },
            { question: "Ales are top-fermented, while lagers are...", answer: "What is Bottom-fermented?", difficulty: 4 },
            { question: "The Reinheitsgebot is a purity law from this country.", answer: "What is Germany?", difficulty: 3 },
            { question: "Malt is typically made from this grain.", answer: "What is Barley?", difficulty: 2 },
            { question: "ABV stands for...", answer: "What is Alcohol By Volume?", difficulty: 1 },
            { question: "The dark color of stouts comes from...", answer: "What is Roasted Malt?", difficulty: 3 },
            { question: "IPA stands for...", answer: "What is India Pale Ale?", difficulty: 2 },
            { question: "The process of heating the wort is called...", answer: "What is Boiling?", difficulty: 2 },
            { question: "Specific Gravity measures the density of the beer relative to...", answer: "What is Water?", difficulty: 4 },
            { question: "The gas produced during fermentation.", answer: "What is Carbon Dioxide?", difficulty: 2 },
            { question: "A session beer is known for having low...", answer: "What is Alcohol Content?", difficulty: 2 },
            { question: "Trappist beers must be brewed by...", answer: "Who are Monks?", difficulty: 3 },
            { question: "The study of fermentation is called...", answer: "What is Zymurgy?", difficulty: 5 },
            { question: "Dry hopping involves adding hops during...", answer: "What is Fermentation/Conditioning?", difficulty: 5 },
            { question: "A growler is a container used to carry...", answer: "What is Beer?", difficulty: 1 },
            { question: "The head on a beer is also called...", answer: "What is Foam?", difficulty: 1 },
            { question: "Brewing involves mashing, laundering, boiling, and...", answer: "What is Fermenting?", difficulty: 2 },
            { question: "A cicerone is a certified expert in...", answer: "What is Beer?", difficulty: 4 }
        ],
        "Alcohol Trivia": [
            { question: "Tequila must be made from this plant.", answer: "What is Blue Agave?", difficulty: 2 },
            { question: "This clear spirit is flavored with juniper berries.", answer: "What is Gin?", difficulty: 2 },
            { question: "Which country drinks the most wine per capita?", answer: "What is The Vatican City?", difficulty: 5 },
            { question: "Mead is an alcoholic beverage made by fermenting this sweet substance.", answer: "What is Honey?", difficulty: 3 },
            { question: "What does the 'VSOP' stand for on a Cognac bottle?", answer: "What is Very Superior Old Pale?", difficulty: 5 },
            { question: "Rum is made from...", answer: "What is Sugarcane/Molasses?", difficulty: 2 },
            { question: "Vodka basically means this in Russian.", answer: "What is Little Water?", difficulty: 4 },
            { question: "Sake is made from...", answer: "What is Rice?", difficulty: 1 },
            { question: "Bourbon must be made in this country.", answer: "What is The United States?", difficulty: 2 },
            { question: "Scotch must be made in this country.", answer: "What is Scotland?", difficulty: 1 },
            { question: "Champagne must be produced in this region of France.", answer: "What is Champagne?", difficulty: 1 },
            { question: "The worm in the bottom of a bottle is actually found in...", answer: "What is Mezcal?", difficulty: 3 },
            { question: "Absinthe was banned for causing...", answer: "What is Hallucinations?", difficulty: 2 },
            { question: "Brandy is made from...", answer: "What is Grapes/Fruit?", difficulty: 2 },
            { question: "Cider is made from...", answer: "What is Apples?", difficulty: 1 },
            { question: "Soju is a popular spirit in...", answer: "What is South Korea?", difficulty: 3 },
            { question: "Baileys is an Irish...?", answer: "What is Cream Liqueur?", difficulty: 2 },
            { question: "Jägermeister contains this many herbs and spices.", answer: "What is 56?", difficulty: 5 },
            { question: "Kahlúa is a liqueur flavored with...", answer: "What is Coffee?", difficulty: 1 },
            { question: "Sambuca is flavored with...", answer: "What is Anise?", difficulty: 4 }
        ],
        "Famous Bars": [
            { question: "The bar where everybody knows your name.", answer: "What is Cheers?", difficulty: 1 },
            { question: "Quant's favorite cantina in Star Wars.", answer: "What is Mos Eisley Cantina?", difficulty: 2 },
            { question: "The pub in Shaun of the Dead.", answer: "What is The Winchester?", difficulty: 3 },
            { question: "The iconic Irish pub in 'It's Always Sunny in Philadelphia'.", answer: "What is Paddy's Pub?", difficulty: 2 },
            { question: "The bar in the Shining.", answer: "What is The Gold Room?", difficulty: 4 },
            { question: "The bar in How I Met Your Mother.", answer: "What is MacLaren's Pub?", difficulty: 3 },
            { question: "The bar in Friends (coffee shop, but iconic).", answer: "What is Central Perk?", difficulty: 1 },
            { question: "The bar in The Simpsons.", answer: "What is Moe's Tavern?", difficulty: 1 },
            { question: "The bar in Family Guy.", answer: "What is The Drunken Clam?", difficulty: 2 },
            { question: "The bar in Casablanca.", answer: "What is Rick's Café Américain?", difficulty: 5 },
            { question: "The bar in Coyote Ugly.", answer: "What is Coyote Ugly?", difficulty: 1 },
            { question: "The fictional bar in Harry Potter.", answer: "What is The Three Broomsticks?", difficulty: 2 },
            { question: "The bar in New Girl.", answer: "What is The Griffin?", difficulty: 4 },
            { question: "The bar in Grey's Anatomy.", answer: "What is Joe's Bar?", difficulty: 3 },
            { question: "The bar in The Sopranos.", answer: "What is Bada Bing!", difficulty: 3 },
            { question: "The bar in True Blood.", answer: "What is Fangtasia?", difficulty: 3 },
            { question: "The bar in Twin Peaks.", answer: "What is The Roadhouse?", difficulty: 4 },
            { question: "The bar in Goodfellas.", answer: "What is The Bamboo Lounge?", difficulty: 5 },
            { question: "The club in Scarface.", answer: "What is The Babylon Club?", difficulty: 5 },
            { question: "The bar in Indiana Jones.", answer: "What is Club Obi Wan?", difficulty: 5 }
        ],
        "Barroom Physics": [
            { question: "The force that keeps foam at the top of a beer.", answer: "What is Buoyancy?", difficulty: 2 },
            { question: "Why a Guinness bubble sinks (circulation patterns).", answer: "What is Drag?", difficulty: 4 },
            { question: "The effect that causes wine legs (tears).", answer: "What is The Marangoni Effect?", difficulty: 5 },
            { question: "Condensation forms on the outside of a cold glass because of this.", answer: "What is Dew Point?", difficulty: 3 },
            { question: "The density of alcohol relative to water (less or more).", answer: "What is Less?", difficulty: 2 },
            { question: "The shape of a liquid droplet is due to...", answer: "What is Surface Tension?", difficulty: 2 },
            { question: "Why ice floats in a drink.", answer: "What is Density (Ice is less dense)?", difficulty: 1 },
            { question: "The sound a bottle makes when you blow across it is resonance.", answer: "What is Resonance?", difficulty: 3 },
            { question: "The Coanda effect explains why liquid...?", answer: "What is Clings to the curved surface of a glass?", difficulty: 5 },
            { question: "The freezing point of alcohol is...?", answer: "What is Lower than water?", difficulty: 1 },
            { question: "Sublimation is when a solid turns directly into...", answer: "What is Gas?", difficulty: 2 },
            { question: "The Leidenfrost effect can be seen when liquid hits...", answer: "What is A hot surface?", difficulty: 4 },
            { question: "The study of fluids in motion.", answer: "What is Fluid Dynamics?", difficulty: 2 },
            { question: "Why a shaken soda explodes (nucleation sites).", answer: "What are Nucleation Sites?", difficulty: 4 },
            { question: "The reason a straw works (pressure).", answer: "What is Atmospheric Pressure?", difficulty: 2 },
            { question: "The meniscus of water in a glass curves...", answer: "What is Up?", difficulty: 3 },
            { question: "The meniscus of mercury in a glass curves...", answer: "What is Down?", difficulty: 3 },
            { question: "The speed of sound travels faster in liquids than in...", answer: "What is Gas?", difficulty: 2 },
            { question: "Refraction makes a straw look...", answer: "What is Bent?", difficulty: 1 },
            { question: "Viscosity is the measure of a fluid's...", answer: "What is Resistance to flow?", difficulty: 3 }
        ]
    }
};
