console.log("Trivia DB Module Evaluating...");

export const library = {
    themes: {
        "standard": { name: "Standard Trivia", categories: ["Before & After", "4-Letter Words", "Science", "English", "Barroom Physics"] },
        "daily": { name: "Daily Mix", categories: [] },
        "booze": { name: "Beers, Bars & Booze", categories: ["Potent Potables", "Pub Grub", "Beer Science", "Alcohol Trivia", "Famous Bars"] },
        "history": { name: "The History Vault", categories: ["US History", "Wars", "Technology", "Ancient Greece", "The 1980s"] },
        "pop": { name: "Pop Culture Blender", categories: ["Blockbuster Movies", "Reality TV", "Slogans & Brands", "Current Events", "Famous People"] },
        "music": { name: "Music Masters", categories: ["Rock n' Roll Riots", "Lyrics about Liquor", "80s One-Hit Wonders", "Rap", "Haus (House Music)"] },
        "geography": { name: "Globe Trotter", categories: ["World Capitals", "Rivers & Lakes", "Mountains", "Islands", "Landmarks"] },
        "sports": { name: "The Sports Bar", categories: ["Olympics", "NFL Legends", "NBA Hoops", "World Cup Soccer", "Baseball History"] },
        "library": { name: "The Library", categories: ["Classic Novels", "Shakespeare", "Poetry", "Children's Books", "Mythology"] },
        "science": { name: "Science Lab", categories: ["Biology", "Physics", "Astronomy", "Chemistry", "Famous Scientists"] },
        "movies": { name: "Silver Screen", categories: ["Oscar Winners", "Disney Villains", "Horror Movies", "Comedies", "Sci-Fi Classics"] }
    },
    pool: {
        "Potent Potables": [
            { question: "The primary ingredient in a Screwdriver.", answer: "What is Vodka?", difficulty: 1 },
            { question: "This Japanese rice wine is often served warm.", answer: "What is Sake?", difficulty: 1 },
            { question: "A Margarita is typically served in a glass rimmed with...", answer: "What is Salt?", difficulty: 1 },
            { question: "This clear spirit is often associated with Russia.", answer: "What is Vodka?", difficulty: 1 },
            { question: "This wine is known for its bubbles.", answer: "What is Champagne?", difficulty: 2 },
            { question: "A Mojito typically contains this herb.", answer: "What is Mint?", difficulty: 2 },
            { question: "This irish stout is known for its creamy head.", answer: "What is Guinness?", difficulty: 2 },
            { question: "A Daiquiri is made with this spirit.", answer: "What is Rum?", difficulty: 2 },
            { question: "This spirit is made from the agave plant.", answer: "What is Tequila?", difficulty: 3 },
            { question: "A White Russian contains vodka, coffee liqueur, and...", answer: "What is Cream?", difficulty: 3 },
            { question: "This liqueur is flavored with orange.", answer: "What is Cointreau (or Triple Sec)?", difficulty: 3 },
            { question: "A Bloody Mary is made with this juice.", answer: "What is Tomato Juice?", difficulty: 3 },
            { question: "This cocktail consists of vodka, ginger beer, and lime juice.", answer: "What is a Moscow Mule?", difficulty: 4 },
            { question: "This drink is made with gin and vermouth and garnished with an olive.", answer: "What is a Martini?", difficulty: 4 },
            { question: "This Italian liqueur is almond-flavored.", answer: "What is Amaretto?", difficulty: 4 },
            { question: "A Piña Colada contains pineapple juice, rum, and...", answer: "What is Coconut Cream?", difficulty: 4 },
            { question: "This Scottish region is famous for its peat-smoked whiskies.", answer: "What is Islay?", difficulty: 5 },
            { question: "A 'perfect' Manhattan uses equal parts of sweet and dry types of this wine.", answer: "What is Vermouth?", difficulty: 5 },
            { question: "This cocktail is made with gin, lemon juice, sugar, and club soda.", answer: "What is a Tom Collins?", difficulty: 5 },
            { question: "This drink is a mix of beer and lemonade.", answer: "What is a Shandy?", difficulty: 5 }
        ],
        "Before & After": [
            { question: "The King of Pop meets a delicious pepperoni pie.", answer: "What is Michael Jackson's Pizza?", difficulty: 1 },
            { question: "A long yellow fruit meets a republic.", answer: "What is Banana Republic?", difficulty: 1 },
            { question: "A grilled sandwich meets a cheesy snack.", answer: "What is Cheese Burger King?", difficulty: 1 },
            { question: "The Star Wars jedi master meets a dairy product.", answer: "What is Yoda Yogurt?", difficulty: 1 },
            { question: "A large flightless bird meets a popular ride-sharing app.", answer: "What is Ostrich Uber?", difficulty: 2 },
            { question: "A tropical fruit meets a tech company logo.", answer: "What is Mango Apple?", difficulty: 2 },
            { question: "A boxing legend meets a cartoon alligator.", answer: "What is Muhammad Ali Gator?", difficulty: 2 },
            { question: "The famous wizard boy meets a pottery maker.", answer: "What is Harry Potter Barn?", difficulty: 2 },
            { question: "A famous secret agent number combines with a convenience store chain.", answer: "What is 007-Eleven?", difficulty: 3 },
            { question: "A high-ranking card in a deck joins forces with a common garden tool.", answer: "What is Ace of Spades?", difficulty: 3 },
            { question: "The first man on the moon meets a strong arm muscle.", answer: "What is Neil Armstrong Bicep?", difficulty: 3 },
            { question: "The capital of France meets a Hilton heiress.", answer: "What is Paris Hilton?", difficulty: 3 },
            { question: "A breakfast pastry circle meets the capital of India.", answer: "What is New Delhi Bagel?", difficulty: 4 },
            { question: "A fast car meets a fictional spy.", answer: "What is Ferrari Bond?", difficulty: 4 },
            { question: "A web-slinging superhero meets a heavy metal band.", answer: "What is Spider-Man Metallica?", difficulty: 4 },
            { question: "The author of 'Dracula' meets a famous cookie.", answer: "What is Bram Stoker's Oreo?", difficulty: 4 },
            { question: "A classic board game of property trading merges with a contagious disease.", answer: "What is Monopoly-nucleosis?", difficulty: 5 },
            { question: "The 16th US President meets a luxury car brand.", answer: "What is Abraham Lincoln Continental?", difficulty: 5 },
            { question: "A famous painter meets a type of pasta.", answer: "What is Pablo Picasso Penne?", difficulty: 5 },
            { question: "A country singer meets a Brooks brother.", answer: "What is Garth Brooks Brothers?", difficulty: 5 }
        ],
        "4-Letter Words": [
            { question: "Not far.", answer: "What is Near?", difficulty: 1 },
            { question: "The opposite of love.", answer: "What is Hate?", difficulty: 1 },
            { question: "To assist.", answer: "What is Help?", difficulty: 1 },
            { question: "A very small amount.", answer: "What is Iota?", difficulty: 5 },
            { question: "To emit a loud, deep cry like a lion.", answer: "What is Roar?", difficulty: 2 },
            { question: "A large body of saltwater.", answer: "What is Seas?", difficulty: 2 },
            { question: "To move rapidly on foot.", answer: "What is Race?", difficulty: 2 },
            { question: "To look at closely.", answer: "What is Gaze?", difficulty: 3 },
            { question: "A part of a poem.", answer: "What is Line?", difficulty: 3 },
            { question: "A sour citrus fruit.", answer: "What is Lime?", difficulty: 1 },
            { question: "The highest point of something.", answer: "What is Apex?", difficulty: 4 },
            { question: "A type of tree with acorns.", answer: "What is Oaks?", difficulty: 2 },
            { question: "A strong wind.", answer: "What is Gale?", difficulty: 4 },
            { question: "To exist.", answer: "What is Be?", difficulty: 3 },
            { question: "A classic card game.", answer: "What is Uno?", difficulty: 1 },
            { question: "A mythical giant.", answer: "What is Ogre?", difficulty: 4 },
            { question: "To walk with a limp.", answer: "What is Limp?", difficulty: 2 },
            { question: "A heavenly body.", answer: "What is Star?", difficulty: 2 },
            { question: "To pull along.", answer: "What is Drag?", difficulty: 3 },
            { question: "A type of fuel.", answer: "What is Coal?", difficulty: 3 }
        ],
        "Science": [
            { question: "The chemical formula for water.", answer: "What is H2O?", difficulty: 1 },
            { question: "This planet has rings.", answer: "What is Saturn?", difficulty: 1 },
            { question: "The center of an atom.", answer: "What is The Nucleus?", difficulty: 2 },
            { question: "The force that keeps us on the ground.", answer: "What is Gravity?", difficulty: 1 },
            { question: "The study of fossils.", answer: "What is Paleontology?", difficulty: 3 },
            { question: "The chemical symbol for Gold.", answer: "What is Au?", difficulty: 3 },
            { question: "The process by which plants convert sunlight into energy.", answer: "What is Photosynthesis?", difficulty: 3 },
            { question: "The hardest natural substance on Earth.", answer: "What is Diamond?", difficulty: 2 },
            { question: "He developed the theory of relativity.", answer: "Who is Albert Einstein?", difficulty: 4 },
            { question: "The speed of light.", answer: "What is 299,792,458 m/s? (approx 300k km/s)", difficulty: 5 },
            { question: "The most abundant gas in the atmosphere.", answer: "What is Nitrogen?", difficulty: 4 },
            { question: "The powerhouse of the cell.", answer: "What is The Mitochondria?", difficulty: 2 },
            { question: "The study of the mind.", answer: "What is Psychology?", difficulty: 2 },
            { question: "This element is needed for breathing.", answer: "What is Oxygen?", difficulty: 1 },
            { question: "The process of a caterpillar turning into a butterfly.", answer: "What is Metamorphosis?", difficulty: 2 },
            { question: "The smallest unit of life.", answer: "What is A Cell?", difficulty: 3 },
            { question: "The chemical symbol for Iron.", answer: "What is Fe?", difficulty: 4 },
            { question: "The Big Bang theory explains this.", answer: "What is The Origin of the Universe?", difficulty: 3 },
            { question: "This scientist discovered penicillin.", answer: "Who is Alexander Fleming?", difficulty: 5 },
            { question: "The red planet.", answer: "What is Mars?", difficulty: 1 }
        ],
        // ... (Repeating pattern for brevity in this tool call, but full file will be written)
        "US History": [
            { question: "The first President of the United States.", answer: "Who is George Washington?", difficulty: 1 },
            { question: "The 16th President of the United States.", answer: "Who is Abraham Lincoln?", difficulty: 1 },
            { question: "The year the Declaration of Independence was signed.", answer: "What is 1776?", difficulty: 2 },
            { question: "The ship the Pilgrims sailed on.", answer: "What is The Mayflower?", difficulty: 2 },
            { question: "The first man on the moon.", answer: "Who is Neil Armstrong?", difficulty: 2 },
            { question: "He gave the 'I Have a Dream' speech.", answer: "Who is Martin Luther King Jr.?", difficulty: 1 },
            { question: "This war was fought between the North and South states.", answer: "What is The Civil War?", difficulty: 1 },
            { question: "The amendment that abolished slavery.", answer: "What is The 13th Amendment?", difficulty: 3 },
            { question: "The year Columbus arrived in the Americas.", answer: "What is 1492?", difficulty: 2 },
            { question: "The 44th President of the United States.", answer: "Who is Barack Obama?", difficulty: 1 },
            { question: "The amendment that gave women the right to vote.", answer: "What is The 19th Amendment?", difficulty: 4 },
            { question: "The date of the Pearl Harbor attack.", answer: "What is December 7, 1941?", difficulty: 4 },
            { question: "He wrote the Declaration of Independence.", answer: "Who is Thomas Jefferson?", difficulty: 3 },
            { question: "The purchase of Alaska was known as this.", answer: "What is Seward's Folly?", difficulty: 5 },
            { question: "The war fought against the British for independence.", answer: "What is The Revolutionary War?", difficulty: 2 },
            { question: "The scandal that forced Nixon to resign.", answer: "What is Watergate?", difficulty: 3 },
            { question: "The document that starts 'We the People'.", answer: "What is The Constitution?", difficulty: 3 },
            { question: "The constitutional ban on alcohol in the US (1920-1933).", answer: "What is Prohibition?", difficulty: 3 },
            { question: "The battle that was the turning point of the Civil War.", answer: "What is Gettysburg?", difficulty: 4 },
            { question: "He is on the $100 bill.", answer: "Who is Benjamin Franklin?", difficulty: 5 }
        ],
        "Wars": [
            { question: "The 'War to End All Wars'.", answer: "What is World War I?", difficulty: 2 },
            { question: "The longest war in US history (until Afghanistan).", answer: "What is The Vietnam War?", difficulty: 3 },
            { question: "The battle that ended Napoleon's rule.", answer: "What is Waterloo?", difficulty: 4 },
            { question: "The 100 Years War was fought between these two countries.", answer: "Who are England and France?", difficulty: 5 },
            { question: "The treaty that ended the Revolutionary War.", answer: "What is The Treaty of Paris?", difficulty: 5 },
            { question: "The war that involved the Axis and Allied powers.", answer: "What is World War II?", difficulty: 1 },
            { question: "The war between North and South Korea.", answer: "What is The Korean War?", difficulty: 2 },
            { question: "The war known as Desert Storm.", answer: "What is The Gulf War?", difficulty: 3 },
            { question: "The war between the US and Mexico in the 1840s.", answer: "What is The Mexican-American War?", difficulty: 4 },
            { question: "The war that lasted from 1939 to 1945.", answer: "What is World War II?", difficulty: 2 },
            { question: "The Cold War was primarily between the US and...", answer: "Who is The Soviet Union?", difficulty: 2 },
            { question: "The war that started in 2003.", answer: "What is The Iraq War?", difficulty: 2 },
            { question: "The battle of Normandy is also known as...", answer: "What is D-Day?", difficulty: 3 },
            { question: "The war that featured trench warfare.", answer: "What is World War I?", difficulty: 3 },
            { question: "The Spanish Civil War took place in this decade.", answer: "What is The 1930s?", difficulty: 5 },
            { question: "The war of 1812 was fought between the US and...", answer: "Who is Great Britain?", difficulty: 4 },
            { question: "The Peloponnesian War was fought between Athens and...", answer: "What is Sparta?", difficulty: 5 },
            { question: "The war that ended with the Treaty of Versailles.", answer: "What is World War I?", difficulty: 4 },
            { question: "The Six-Day War took place in this region.", answer: "What is The Middle East?", difficulty: 4 },
            { question: "The Franco-Prussian War led to the unification of...", answer: "What is Germany?", difficulty: 5 }
        ],
        "Technology": [
            { question: "This company was founded in a garage in Los Altos in 1976.", answer: "What is Apple?", difficulty: 1 },
            { question: "The precursor to the internet, developed by the US Department of Defense.", answer: "What is ARPANET?", difficulty: 3 },
            { question: "This man invented the World Wide Web.", answer: "Who is Tim Berners-Lee?", difficulty: 2 },
            { question: "The first mechanical computer designed by Charles Babbage.", answer: "What is The Analytical Engine?", difficulty: 4 },
            { question: "The first computer programmer.", answer: "Who is Ada Lovelace?", difficulty: 4 },
            { question: "This device replaced vacuum tubes in computers.", answer: "What is The Transistor?", difficulty: 2 },
            { question: "The year the first iPhone was released.", answer: "What is 2007?", difficulty: 1 },
            { question: "The search engine that was originally called 'BackRub'.", answer: "What is Google?", difficulty: 3 },
            { question: "He sent the first wireless radio transmission.", answer: "Who is Guglielmo Marconi?", difficulty: 5 },
            { question: "The name of the first electronic general-purpose digital computer.", answer: "What is ENIAC?", difficulty: 3 },
            { question: "This operating system was created by Linus Torvalds.", answer: "What is Linux?", difficulty: 2 },
            { question: "The company that released the Walkman.", answer: "What is Sony?", difficulty: 1 },
            { question: "The man known as the father of modern computing (broke Enigma code).", answer: "Who is Alan Turing?", difficulty: 2 },
            { question: "The first video game console for the home (1972).", answer: "What is The Magnavox Odyssey?", difficulty: 5 },
            { question: "The year Y2K was a concern.", answer: "What is 2000?", difficulty: 1 },
            { question: "The programming language created by Grace Hopper.", answer: "What is COBOL?", difficulty: 4 },
            { question: "This company introduced the first IBM PC.", answer: "What is IBM?", difficulty: 1 },
            { question: "The first browser to popularize the web.", answer: "What is Mosaic (or Netscape)?", difficulty: 4 },
            { question: "The year Facebook was launched.", answer: "What is 2004?", difficulty: 3 },
            { question: "The rover that landed on Mars in 2012.", answer: "What is Curiosity?", difficulty: 2 }
        ],
        "Ancient Greece": [
            { question: "The King of the Greek Gods.", answer: "Who is Zeus?", difficulty: 1 },
            { question: "This city-state was known for its military discipline.", answer: "What is Sparta?", difficulty: 2 },
            { question: "He wrote The Iliad and The Odyssey.", answer: "Who is Homer?", difficulty: 3 },
            { question: "The temple dedicated to Athena on the Acropolis.", answer: "What is The Parthenon?", difficulty: 4 },
            { question: "The philosopher sentenced to death by hemlock.", answer: "Who is Socrates?", difficulty: 4 },
            { question: "The goddess of love and beauty.", answer: "Who is Aphrodite?", difficulty: 2 },
            { question: "The god of the sea.", answer: "Who is Poseidon?", difficulty: 2 },
            { question: "The hero who completed 12 labors.", answer: "Who is Hercules?", difficulty: 1 },
            { question: "The messenger of the gods.", answer: "Who is Hermes?", difficulty: 3 },
            { question: "The goddess of wisdom.", answer: "Who is Athena?", difficulty: 2 },
            { question: "The mythical creature with snakes for hair.", answer: "Who is Medusa?", difficulty: 2 },
            { question: "The city-state known for democracy.", answer: "What is Athens?", difficulty: 2 },
            { question: "The war between the Greeks and Trojans.", answer: "What is The Trojan War?", difficulty: 2 },
            { question: "The wooden horse used to enter Troy.", answer: "What is The Trojan Horse?", difficulty: 1 },
            { question: "The home of the gods.", answer: "What is Mount Olympus?", difficulty: 1 },
            { question: "The god of the underworld.", answer: "Who is Hades?", difficulty: 2 },
            { question: "The philosopher who was a student of Socrates.", answer: "Who is Plato?", difficulty: 5 },
            { question: "The philosopher who was a student of Plato.", answer: "Who is Aristotle?", difficulty: 5 },
            { question: "The games held every four years in Olympia.", answer: "What are The Olympics?", difficulty: 3 },
            { question: "The sea monster with many heads.", answer: "What is The Hydra?", difficulty: 4 }
        ],
        "The 1980s": [
            { question: "This wall came down in 1989.", answer: "What is The Berlin Wall?", difficulty: 2 },
            { question: "The US President for most of the decade.", answer: "Who is Ronald Reagan?", difficulty: 2 },
            { question: "The space shuttle that tragically exploded in 1986.", answer: "What is Challenger?", difficulty: 3 },
            { question: "This musical format overtook vinyl sales in 1988.", answer: "What are Cassette Tapes?", difficulty: 4 },
            { question: "The event held in Philadelphia and London to fight famine in Ethiopia.", answer: "What is Live Aid?", difficulty: 5 },
            { question: "This 1982 Spielberg film features a friendly alien who wants to phone home.", answer: "What is E.T. the Extra-Terrestrial?", difficulty: 1 },
            { question: "The singer known as the Material Girl.", answer: "Who is Madonna?", difficulty: 1 },
            { question: "The video game featuring a yellow circle eating dots.", answer: "What is Pac-Man?", difficulty: 1 },
            { question: "The Rubik's Cube became a craze in this decade.", answer: "What are The 80s? (Rubik's Cube)", difficulty: 2 },
            { question: "The movie where 'Nobody puts Baby in a corner'.", answer: "What is Dirty Dancing?", difficulty: 3 },
            { question: "The TV show set in a bar where everyone knows your name.", answer: "What is Cheers?", difficulty: 2 },
            { question: "The singer of 'Thriller'.", answer: "Who is Michael Jackson?", difficulty: 1 },
            { question: "The console released by Nintendo in 1985 (US).", answer: "What is The NES?", difficulty: 3 },
            { question: "The movie involving a DeLorean time machine.", answer: "What is Back to the Future?", difficulty: 1 },
            { question: "The band that sang 'Don't Stop Believin''.", answer: "Who are Journey?", difficulty: 2 },
            { question: "The royal wedding of 1981 was between Charles and...", answer: "Who is Diana?", difficulty: 2 },
            { question: "The disaster at a nuclear power plant in 1986.", answer: "What is Chernobyl?", difficulty: 3 },
            { question: "The term for young urban professionals.", answer: "What are Yuppies?", difficulty: 4 },
            { question: "The movie with the line 'I'll be back'.", answer: "What is The Terminator?", difficulty: 1 },
            { question: "The song 'Eye of the Tiger' is from this movie.", answer: "What is Rocky III?", difficulty: 4 }
        ],
        "English": [
            { question: "26 letters make up this set.", answer: "What is The Alphabet?", difficulty: 1 },
            { question: "A word that names a person, place, or thing.", answer: "What is a Noun?", difficulty: 1 },
            { question: "The past tense of 'run'.", answer: "What is Ran?", difficulty: 1 },
            { question: "A punctuation mark used to indicate a pause stronger than a comma.", answer: "What is a Semicolon?", difficulty: 3 },
            { question: "The study of the origin of words.", answer: "What is Etymology?", difficulty: 5 },
            { question: "A word that describes a noun.", answer: "What is an Adjective?", difficulty: 2 },
            { question: "A word that describes a verb.", answer: "What is an Adverb?", difficulty: 2 },
            { question: "Two words that sound the same but have different meanings.", answer: "What are Homophones?", difficulty: 3 },
            { question: "A short story with a moral, often featuring animals.", answer: "What is a Fable?", difficulty: 3 },
            { question: "The person telling the story.", answer: "Who is The Narrator?", difficulty: 2 },
            { question: "A comparison using 'like' or 'as'.", answer: "What is a Simile?", difficulty: 2 },
            { question: "A comparison not using 'like' or 'as'.", answer: "What is a Metaphor?", difficulty: 3 },
            { question: "Giving human qualities to non-human things.", answer: "What is Personification?", difficulty: 4 },
            { question: "The main character in a story.", answer: "Who is The Protagonist?", difficulty: 3 },
            { question: "The opponent of the main character.", answer: "Who is The Antagonist?", difficulty: 3 },
            { question: "A 14-line poem.", answer: "What is a Sonnet?", difficulty: 4 },
            { question: "The repetition of initial consonant sounds.", answer: "What is Alliteration?", difficulty: 4 },
            { question: "The use of words that imitate sounds.", answer: "What is Onomatopoeia?", difficulty: 5 },
            { question: "A statement that seems contradictory but may be true.", answer: "What is a Paradox?", difficulty: 5 },
            { question: "The feeling created in the reader by a literary work.", answer: "What is Mood?", difficulty: 4 }
        ],
        "Blockbuster Movies": [
            { question: "This 2009 James Cameron film is the highest-grossing movie of all time.", answer: "What is Avatar?", difficulty: 1 },
            { question: "This movie features a sinking ship and Leo DiCaprio.", answer: "What is Titanic?", difficulty: 1 },
            { question: "The first movie in the MCU (Marvel Cinematic Universe).", answer: "What is Iron Man?", difficulty: 2 },
            { question: "The dinosaur movie directed by Steven Spielberg in 1993.", answer: "What is Jurassic Park?", difficulty: 1 },
            { question: "This animated movie features a lion cub named Simba.", answer: "What is The Lion King?", difficulty: 1 },
            { question: "The movie where Heath Ledger played the Joker.", answer: "What is The Dark Knight?", difficulty: 2 },
            { question: "This movie is set on a desert planet called Arrakis.", answer: "What is Dune?", difficulty: 3 },
            { question: "The first Star Wars movie released (Episode IV).", answer: "What is A New Hope?", difficulty: 2 },
            { question: "This movie gave us the quote 'May the odds be ever in your favor'.", answer: "What is The Hunger Games?", difficulty: 2 },
            { question: "The highest grossing animated movie of all time (as of 2024).", answer: "What is Inside Out 2?", difficulty: 3 },
            { question: "Tom Cruise flies jets in this franchise.", answer: "What is Top Gun?", difficulty: 1 },
            { question: "This movie features blue people on Pandora.", answer: "What is Avatar?", difficulty: 1 },
            { question: "The movie about a doll living in a plastic world.", answer: "What is Barbie?", difficulty: 1 },
            { question: "This 1975 movie terrified people of going into the water.", answer: "What is Jaws?", difficulty: 2 },
            { question: "The Lord of the Rings movie that won 11 Oscars.", answer: "What is The Return of the King?", difficulty: 4 },
            { question: "This movie features the song 'Let It Go'.", answer: "What is Frozen?", difficulty: 1 },
            { question: "The director of Oppenheimer.", answer: "Who is Christopher Nolan?", difficulty: 3 },
            { question: "The first Avengers movie was released in this year.", answer: "What is 2012?", difficulty: 4 },
            { question: "This movie is the highest grossing R-rated film.", answer: "What is Deadpool & Wolverine (or Joker depending on date)?", difficulty: 3 },
            { question: "The name of the skyscraper in Die Hard.", answer: "What is Nakatomi Plaza?", difficulty: 5 }
        ],
        "Reality TV": [
            { question: "This family has kept up with audiences for over a decade.", answer: "Who are The Kardashians?", difficulty: 1 },
            { question: "Contestants try to outwit, outplay, and outlast on this show.", answer: "What is Survivor?", difficulty: 1 },
            { question: "Gordon Ramsay yells at aspiring chefs in this kitchen.", answer: "What is Hell's Kitchen?", difficulty: 2 },
            { question: "This show features drag queens competing for the crown.", answer: "What is RuPaul's Drag Race?", difficulty: 2 },
            { question: "The shore house in this MTV show was located in Seaside Heights.", answer: "What is Jersey Shore?", difficulty: 2 },
            { question: "The social experiment show where partners wed upon first meeting.", answer: "What is Married at First Sight?", difficulty: 3 },
            { question: "The show where finding love is an island adventure.", answer: "What is Love Island?", difficulty: 3 },
            { question: "The show featuring the 'Real Housewives'.", answer: "What is The Real Housewives?", difficulty: 1 },
            { question: "The show where entrepreneurs pitch to investors.", answer: "What is Shark Tank?", difficulty: 2 },
            { question: "The show where singers compete with turning chairs.", answer: "What is The Voice?", difficulty: 2 },
            { question: "The show where celebrities dance with professionals.", answer: "What is Dancing with the Stars?", difficulty: 2 },
            { question: "The show about a pawn shop in Las Vegas.", answer: "What is Pawn Stars?", difficulty: 3 },
            { question: "The show about storage locker auctions.", answer: "What is Storage Wars?", difficulty: 3 },
            { question: "The show about online dating deceptions and fake profiles.", answer: "What is Catfish?", difficulty: 3 },
            { question: "The reality show featuring the Duggar family.", answer: "What is 19 Kids and Counting?", difficulty: 4 },
            { question: "The show about extreme home makeovers.", answer: "What is Extreme Makeover: Home Edition?", difficulty: 4 },
            { question: "The show where people race around the world.", answer: "What is The Amazing Race?", difficulty: 4 },
            { question: "The show featuring Abby Lee Miller's studio.", answer: "What is Dance Moms?", difficulty: 4 },
            { question: "The show involving bachelors and roses.", answer: "What is The Bachelor?", difficulty: 1 },
            { question: "The show following deckhands on a yacht.", answer: "What is Below Deck?", difficulty: 5 }
        ],
        "Slogans & Brands": [
            { question: "'Just Do It'.", answer: "What is Nike?", difficulty: 1 },
            { question: "'I'm Lovin' It'.", answer: "What is McDonald's?", difficulty: 1 },
            { question: "'Taste the Rainbow'.", answer: "What is Skittles?", difficulty: 1 },
            { question: "'Finger Lickin' Good'.", answer: "What is KFC?", difficulty: 1 },
            { question: "'Melts in your mouth, not in your hands'.", answer: "What are M&Ms?", difficulty: 2 },
            { question: "'The Happiest Place on Earth'.", answer: "What is Disneyland?", difficulty: 1 },
            { question: "'Think Different'.", answer: "What is Apple?", difficulty: 2 },
            { question: "'Because You're Worth It'.", answer: "What is L'Oréal?", difficulty: 3 },
            { question: "'Eat Fresh'.", answer: "What is Subway?", difficulty: 1 },
            { question: "'Red Bull gives you...'", answer: "What are Wings?", difficulty: 1 },
            { question: "'The Ultimate Driving Machine'.", answer: "What is BMW?", difficulty: 3 },
            { question: "'Maybe she's born with it. Maybe it's...'", answer: "What is Maybelline?", difficulty: 2 },
            { question: "'Have a break, have a...'", answer: "What is KitKat?", difficulty: 1 },
            { question: "'Open Happiness'.", answer: "What is Coca-Cola?", difficulty: 3 },
            { question: "'America Runs on...'", answer: "What is Dunkin'?", difficulty: 2 },
            { question: "'Belong Anywhere'.", answer: "What is Airbnb?", difficulty: 4 },
            { question: "'Can you hear me now?'.", answer: "What is Verizon?", difficulty: 3 },
            { question: "'What's in your wallet?'.", answer: "What is Capital One?", difficulty: 2 },
            { question: "'Shave Time. Shave Money.'.", answer: "What is Dollar Shave Club?", difficulty: 4 },
            { question: "'Move Fast and Break Things' (Original motto).", answer: "What is Facebook?", difficulty: 5 }
        ],
        "Current Events": [
            { question: "The platform formerly known as Twitter.", answer: "What is X?", difficulty: 1 },
            { question: "This AI chatbot started a revolution in 2022.", answer: "What is ChatGPT?", difficulty: 1 },
            { question: "This country hosted the 2024 Summer Olympics.", answer: "What is France?", difficulty: 2 },
            { question: "The movie that famously battled 'Barbie' at the box office.", answer: "What is Oppenheimer?", difficulty: 2 },
            { question: "This crypto exchange collapsed spectacularly involving Sam Bankman-Fried.", answer: "What is FTX?", difficulty: 4 },
            { question: "The OceanGate vessel that was lost during a Titanic expedition.", answer: "What is The Titan?", difficulty: 3 },
            { question: "The King crowned in England in 2023.", answer: "Who is King Charles III?", difficulty: 2 },
            { question: "The tech company that released the Vision Pro.", answer: "What is Apple?", difficulty: 3 },
            { question: "The singer who dated Travis Kelce.", answer: "Who is Taylor Swift?", difficulty: 1 },
            { question: "The wildfire that devastated Maui.", answer: "What is The Lahaina Fire?", difficulty: 4 },
            { question: "The country that invaded Ukraine in 2022.", answer: "What is Russia?", difficulty: 1 },
            { question: "The app that ByteDance owns.", answer: "What is TikTok?", difficulty: 2 },
            { question: "The huge sphere venue in Las Vegas.", answer: "What is The Sphere?", difficulty: 2 },
            { question: "The actor who played Ken in Barbie.", answer: "Who is Ryan Gosling?", difficulty: 2 },
            { question: "The trial involving Johnny Depp and...", answer: "Who is Amber Heard?", difficulty: 2 },
            { question: "The winner of the 2022 FIFA World Cup.", answer: "What is Argentina?", difficulty: 3 },
            { question: "The streaming service that cracks down on password sharing.", answer: "What is Netflix?", difficulty: 2 },
            { question: "The strikes that halted Hollywood.", answer: "What are The SAG-AFTRA/WGA Strikes?", difficulty: 4 },
            { question: "The variant of COVID-19 named after a Greek letter O.", answer: "What is Omicron?", difficulty: 3 },
            { question: "The planet showing signs of potential life (Phosphine).", answer: "What is Venus?", difficulty: 5 }
        ],
        "Famous People": [
            { question: "The founder of Tesla and SpaceX.", answer: "Who is Elon Musk?", difficulty: 1 },
            { question: "This singer is known for her 'Eras' tour.", answer: "Who is Taylor Swift?", difficulty: 1 },
            { question: "The actor who played Iron Man.", answer: "Who is Robert Downey Jr.?", difficulty: 2 },
            { question: "This British Prince released a memoir titled 'Spare'.", answer: "Who is Prince Harry?", difficulty: 3 },
            { question: "He slapped Chris Rock at the Oscars.", answer: "Who is Will Smith?", difficulty: 2 },
            { question: "The Queen of Pop.", answer: "Who is Madonna?", difficulty: 2 },
            { question: "The King of Rock and Roll.", answer: "Who is Elvis Presley?", difficulty: 1 },
            { question: "The first black President of the US.", answer: "Who is Barack Obama?", difficulty: 1 },
            { question: "The founder of Microsoft.", answer: "Who is Bill Gates?", difficulty: 2 },
            { question: "The founder of Amazon.", answer: "Who is Jeff Bezos?", difficulty: 2 },
            { question: "The author of Harry Potter.", answer: "Who is J.K. Rowling?", difficulty: 2 },
            { question: "Starting in Chicago, she became the queen of daytime talk.", answer: "Who is Oprah Winfrey?", difficulty: 1 },
            { question: "The actor known as 'The Rock'.", answer: "Who is Dwayne Johnson?", difficulty: 2 },
            { question: "The singer of 'Rolling in the Deep'.", answer: "Who is Adele?", difficulty: 3 },
            { question: "The painter of the Mona Lisa.", answer: "Who is Leonardo da Vinci?", difficulty: 3 },
            { question: "The scientist who formulated gravity.", answer: "Who is Isaac Newton?", difficulty: 4 },
            { question: "The Civil Rights leader.", answer: "Who is Martin Luther King Jr.?", difficulty: 2 },
            { question: "The first woman to fly across the Atlantic.", answer: "Who is Amelia Earhart?", difficulty: 4 },
            { question: "The boxer known as 'The Greatest'.", answer: "Who is Muhammad Ali?", difficulty: 3 },
            { question: "The creator of Mickey Mouse.", answer: "Who is Walt Disney?", difficulty: 2 }
        ],
        "Rock n' Roll Riots": [
            { question: "This band sang 'I Wanna Be Sedated'.", answer: "Who are The Ramones?", difficulty: 3 },
            { question: "He smashed his guitar on stage, defining The Who.", answer: "Who is Pete Townshend?", difficulty: 4 },
            { question: "The lead singer of The Rolling Stones.", answer: "Who is Mick Jagger?", difficulty: 1 },
            { question: "This festival in 1999 ended in fires and riots.", answer: "What is Woodstock '99?", difficulty: 3 },
            { question: "The band known for the song 'Smells Like Teen Spirit'.", answer: "Who are Nirvana?", difficulty: 1 },
            { question: "The band that released 'Dark Side of the Moon'.", answer: "Who are Pink Floyd?", difficulty: 2 },
            { question: "The guitarist who played 'Eruption'.", answer: "Who is Eddie Van Halen?", difficulty: 2 },
            { question: "The drummer for Led Zeppelin.", answer: "Who is John Bonham?", difficulty: 5 },
            { question: "The band known as the Fab Four.", answer: "Who are The Beatles?", difficulty: 1 },
            { question: "The singer known as the Lizard King.", answer: "Who is Jim Morrison?", difficulty: 4 },
            { question: "The band that sings 'Bohemian Rhapsody'.", answer: "Who are Queen?", difficulty: 1 },
            { question: "The singer of 'Born to Run'.", answer: "Who is Bruce Springsteen?", difficulty: 2 },
            { question: "The band featuring Axl Rose and Slash.", answer: "Who are Guns N' Roses?", difficulty: 2 },
            { question: "The bassist for the Red Hot Chili Peppers.", answer: "Who is Flea?", difficulty: 3 },
            { question: "The band that wrote 'Stairway to Heaven'.", answer: "Who are Led Zeppelin?", difficulty: 2 },
            { question: "The singer known for painting his face (KISS).", answer: "Who is Gene Simmons?", difficulty: 3 },
            { question: "The band that sang 'Hotel California'.", answer: "Who are The Eagles?", difficulty: 2 },
            { question: "The artist known as Ziggy Stardust.", answer: "Who is David Bowie?", difficulty: 4 },
            { question: "The band called 'The bad boys from Boston'.", answer: "Who are Aerosmith?", difficulty: 3 },
            { question: "The grunge band fronted by Chris Cornell.", answer: "Who are Soundgarden?", difficulty: 5 }
        ],
        "Lyrics about Liquor": [
            { question: "'It's five o'clock somewhere'.", answer: "Who is Alan Jackson?", difficulty: 1 },
            { question: "'Tequila makes her clothes fall off'.", answer: "Who is Joe Nichols?", difficulty: 4 },
            { question: "'Red red wine, you make me feel so fine'.", answer: "Who are UB40?", difficulty: 2 },
            { question: "'I got friends in low places, where the whiskey drowns...'.", answer: "Who is Garth Brooks?", difficulty: 1 },
            { question: "'One bourbon, one scotch, and one beer'.", answer: "Who is George Thorogood?", difficulty: 4 },
            { question: "'I love this bar'.", answer: "Who is Toby Keith?", difficulty: 3 },
            { question: "'Margaritaville'.", answer: "Who is Jimmy Buffett?", difficulty: 1 },
            { question: "'Whiskey River, take my mind'.", answer: "Who is Willie Nelson?", difficulty: 2 },
            { question: "'Piano Man' mentions 'sharing a drink they call loneliness'.", answer: "Who is Billy Joel?", difficulty: 2 },
            { question: "'Beer for my horses'.", answer: "Who are Toby Keith and Willie Nelson?", difficulty: 3 },
            { question: "'Strawberry Wine'.", answer: "Who is Deana Carter?", difficulty: 5 },
            { question: "'Tennessee Whiskey'.", answer: "Who is Chris Stapleton?", difficulty: 2 },
            { question: "'Tubthumping' (I get knocked down...).", answer: "Who are Chumbawamba?", difficulty: 3 },
            { question: "'Brass Monkey'.", answer: "Who are The Beastie Boys?", difficulty: 3 },
            { question: "'Gin and Juice'.", answer: "Who is Snoop Dogg?", difficulty: 1 },
            { question: "'Shots' feat. Lil Jon.", answer: "Who are LMFAO?", difficulty: 2 },
            { question: "'Cheers (Drink to That)'.", answer: "Who is Rihanna?", difficulty: 2 },
            { question: "'Blame It (On the Alcohol)'.", answer: "Who is Jamie Foxx?", difficulty: 3 },
            { question: "'Tipsy'.", answer: "Who is J-Kwon?", difficulty: 5 },
            { question: "'Bottoms Up'.", answer: "Who is Trey Songz?", difficulty: 5 }
        ],
        "80s One-Hit Wonders": [
            { question: "'Come on Eileen'.", answer: "Who are Dexys Midnight Runners?", difficulty: 1 },
            { question: "'Take On Me'.", answer: "Who are A-ha?", difficulty: 1 },
            { question: "'I melt with you'.", answer: "Who are Modern English?", difficulty: 3 },
            { question: "'867-5309/Jenny'.", answer: "Who are Tommy Tutone?", difficulty: 2 },
            { question: "'Turning Japanese'.", answer: "Who are The Vapors?", difficulty: 4 },
            { question: "'Tainted Love'.", answer: "Who are Soft Cell?", difficulty: 2 },
            { question: "'Relax'.", answer: "Who are Frankie Goes to Hollywood?", difficulty: 2 },
            { question: "'Whip It'.", answer: "Who are Devo?", difficulty: 2 },
            { question: "'Video Killed the Radio Star'.", answer: "Who are The Buggles?", difficulty: 3 },
            { question: "'Safety Dance'.", answer: "Who are Men Without Hats?", difficulty: 3 },
            { question: "'Too Shy'.", answer: "Who are Kajagoogoo?", difficulty: 1 },
            { question: "'Mickey'.", answer: "Who is Toni Basil?", difficulty: 4 },
            { question: "'She Blinded Me with Science'.", answer: "Who is Thomas Dolby?", difficulty: 4 },
            { question: "'99 Luftballons'.", answer: "Who is Nena?", difficulty: 2 },
            { question: "'Puttin' on the Ritz'.", answer: "Who is Taco?", difficulty: 5 },
            { question: "'Walking on Sunshine'.", answer: "Who are Katrina and the Waves?", difficulty: 2 },
            { question: "'Pass the Dutchie'.", answer: "Who are Musical Youth?", difficulty: 5 },
            { question: "'Funkytown'.", answer: "Who are Lipps Inc.?", difficulty: 3 },
            { question: "'Electric Avenue'.", answer: "Who is Eddy Grant?", difficulty: 3 },
            { question: "'My Sharona'.", answer: "Who are The Knack?", difficulty: 2 }
        ],
        "Rap": [
            { question: "He is known as the 'Rap God'.", answer: "Who is Eminem?", difficulty: 1 },
            { question: "This Canadian rapper started on Degrassi.", answer: "Who is Drake?", difficulty: 1 },
            { question: "This group said 'Fight the Power'.", answer: "Who are Public Enemy?", difficulty: 4 },
            { question: "He released 'The Blueprint'.", answer: "Who is Jay-Z?", difficulty: 2 },
            { question: "This Kendrick Lamar album won a Pulitzer Prize.", answer: "What is DAMN.?", difficulty: 5 },
            { question: "The rapper who died in 1996.", answer: "Who is Tupac Shakur?", difficulty: 2 },
            { question: "The rapper who died in 1997.", answer: "Who is Notorious B.I.G.?", difficulty: 2 },
            { question: "The group consisting of Dr. Dre, Ice Cube, etc.", answer: "Who are N.W.A.?", difficulty: 3 },
            { question: "The rapper known for 'Gold Digger'.", answer: "Who is Kanye West?", difficulty: 1 },
            { question: "The rapper from Detroit.", answer: "Who is Eminem?", difficulty: 1 },
            { question: "The female rapper known for 'Super Bass'.", answer: "Who is Nicki Minaj?", difficulty: 2 },
            { question: "The rapper known for 'Bodak Yellow'.", answer: "Who is Cardi B?", difficulty: 2 },
            { question: "The rapper who founded Bad Boy Records.", answer: "Who is Diddy?", difficulty: 3 },
            { question: "The group known for 'C.R.E.A.M.'.", answer: "Who are Wu-Tang Clan?", difficulty: 3 },
            { question: "The rapper known for 'In Da Club'.", answer: "Who is 50 Cent?", difficulty: 2 },
            { question: "The rapper known for 'Hotline Bling'.", answer: "Who is Drake?", difficulty: 1 },
            { question: "The rapper known for 'SICKO MODE'.", answer: "Who is Travis Scott?", difficulty: 3 },
            { question: "The rapper known for 'Old Town Road'.", answer: "Who is Lil Nas X?", difficulty: 2 },
            { question: "The rapper known for 'Stan'.", answer: "Who is Eminem?", difficulty: 3 },
            { question: "The rapper known for 'Ms. Jackson'.", answer: "Who are OutKast?", difficulty: 3 }
        ],
        "Haus (House Music)": [
            { question: "This French duo wore robot helmets.", answer: "Who are Daft Punk?", difficulty: 1 },
            { question: "The Chicago venue established by Robert Williams in 1977.", answer: "What is The Warehouse?", difficulty: 4 },
            { question: "This DJ released 'Levels'.", answer: "Who is Avicii?", difficulty: 2 },
            { question: "They released 'One More Time'.", answer: "Who are Daft Punk?", difficulty: 1 },
            { question: "The BPM range typical for House music.", answer: "What is 115-130 BPM?", difficulty: 4 },
            { question: "The warehouse in Chicago often cited as the birthplace.", answer: "What is The Warehouse?", difficulty: 5 },
            { question: "The DJ known as the Godfather of House.", answer: "Who is Frankie Knuckles?", difficulty: 5 },
            { question: "The subgenre known for acid sounds.", answer: "What is Acid House?", difficulty: 3 },
            { question: "The island famous for house music parties.", answer: "What is Ibiza?", difficulty: 2 },
            { question: "The group known for 'Don't You Worry Child'.", answer: "Who are Swedish House Mafia?", difficulty: 2 },
            { question: "The DJ known for 'Titanium'.", answer: "Who is David Guetta?", difficulty: 2 },
            { question: "The DJ known for 'Summer'.", answer: "Who is Calvin Harris?", difficulty: 2 },
            { question: "The duo known for 'Closer'.", answer: "Who are The Chainsmokers?", difficulty: 2 },
            { question: "The DJ known for throwing cake.", answer: "Who is Steve Aoki?", difficulty: 3 },
            { question: "The electronic instrument crucial for Acid House.", answer: "What is The Roland TB-303?", difficulty: 5 },
            { question: "The festival in Belgium dedicated to electronic music.", answer: "What is Tomorrowland?", difficulty: 3 },
            { question: "The DJ known for a mouse helmet.", answer: "Who is Deadmau5?", difficulty: 1 },
            { question: "The DJ known for 'Scary Monsters and Nice Sprites'.", answer: "Who is Skrillex?", difficulty: 2 },
            { question: "The song 'Sandstorm'.", answer: "Who is Darude?", difficulty: 1 },
            { question: "The subgenre known for deeper, soulful sounds.", answer: "What is Deep House?", difficulty: 4 }
        ],
        "Pub Grub": [
            { question: "This 'fishy' dish paired with chips is a staple of British pub culture.", answer: "What is Fish and Chips?", difficulty: 1 },
            { question: "Invented in Buffalo, NY, these spicy poultry pieces are a bar favorite.", answer: "What are Buffalo Wings?", difficulty: 1 },
            { question: "This purely Canadian dish features fries, cheese curds, and gravy.", answer: "What is Poutine?", difficulty: 2 },
            { question: "Typically pickled and served in massive jars on bars.", answer: "What are Pickled Eggs?", difficulty: 3 },
            { question: "This 'Ploughman's' meal was promoted to sell more of this dairy product.", answer: "What is Cheese?", difficulty: 5 },
            { question: "A scotch egg is a hard-boiled egg wrapped in...", answer: "What is Sausage Meat?", difficulty: 3 },
            { question: "Bangers and Mash refers to sausages and...", answer: "What are Mashed Potatoes?", difficulty: 2 },
            { question: "A Shepherd's Pie is typically made with this meat.", answer: "What is Lamb?", difficulty: 2 },
            { question: "Toad in the Hole involves sausages cooked in...", answer: "What is Yorkshire Pudding Batter?", difficulty: 4 },
            { question: "Nachos originated in this country.", answer: "What is Mexico?", difficulty: 1 },
            { question: "Mozzarella sticks are typically served with this sauce.", answer: "What is Marinara?", difficulty: 1 },
            { question: "A slider is a small version of this.", answer: "What is A Hamburger?", difficulty: 1 },
            { question: "Fried calamari is made from this sea creature.", answer: "What is Squid?", difficulty: 2 },
            { question: "Jalapeño poppers are often filled with...", answer: "What is Cream Cheese?", difficulty: 2 },
            { question: "A pretzel is often dipped in this yellow condiment.", answer: "What is Mustard?", difficulty: 1 },
            { question: "Onion rings are onions dipped in...", answer: "What is Batter?", difficulty: 2 },
            { question: "Potato skins are often topped with bacon and...", answer: "What is Cheese?", difficulty: 2 },
            { question: "Chili cheese fries are fries topped with...", answer: "What is Chili and Cheese?", difficulty: 1 },
            { question: "A BLT stands for...", answer: "What is Bacon, Lettuce, Tomato?", difficulty: 1 },
            { question: "A Reuben sandwich contains this meat.", answer: "What is Corned Beef?", difficulty: 3 }
        ],
        "Beer Science": [
            { question: "This four-letter ingredient provides bitterness and aroma to beer.", answer: "What are Hops?", difficulty: 1 },
            { question: "This microorganism is responsible for fermentation.", answer: "What is Yeast?", difficulty: 2 },
            { question: "This scale measures the bitterness of beer.", answer: "What is IBU (International Key Bitterness Units)?", difficulty: 3 },
            { question: "Ales are top-fermented, while lagers are...", answer: "What is Bottom-fermented?", difficulty: 4 },
            { question: "The Reinheitsgebot is a purity law from this country.", answer: "What is Germany?", difficulty: 3 },
            { question: "Malt is typically made from this grain.", answer: "What is Barley?", difficulty: 2 },
            { question: "ABV stands for...", answer: "What is Alcohol By Volume?", difficulty: 1 },
            { question: "The dark color of stouts comes from...", answer: "What is Roasted Malt?", difficulty: 3 },
            { question: "IPA stands for...", answer: "What is India Pale Ale?", difficulty: 2 },
            { question: "The process of heating the wort is called...", answer: "What is Boiling?", difficulty: 2 },
            { question: "Specific Gravity measures the density of the beer relative to...", answer: "What is Water?", difficulty: 4 },
            { question: "The gas produced during fermentation.", answer: "What is Carbon Dioxide?", difficulty: 2 },
            { question: "A session beer is known for having low...", answer: "What is Alcohol Content?", difficulty: 2 },
            { question: "Trappist beers must be brewed by...", answer: "Who are Monks?", difficulty: 3 },
            { question: "The study of fermentation is called...", answer: "What is Zymurgy?", difficulty: 5 },
            { question: "Dry hopping involves adding hops during...", answer: "What is Fermentation/Conditioning?", difficulty: 5 },
            { question: "A growler is a container used to carry...", answer: "What is Beer?", difficulty: 1 },
            { question: "The head on a beer is also called...", answer: "What is Foam?", difficulty: 1 },
            { question: "Brewing involves mashing, laundering, boiling, and...", answer: "What is Fermenting?", difficulty: 2 },
            { question: "A cicerone is a certified expert in...", answer: "What is Beer?", difficulty: 4 }
        ],
        "Alcohol Trivia": [
            { question: "Tequila must be made from this plant.", answer: "What is Blue Agave?", difficulty: 2 },
            { question: "This clear spirit is flavored with juniper berries.", answer: "What is Gin?", difficulty: 2 },
            { question: "Which country drinks the most wine per capita?", answer: "What is The Vatican City?", difficulty: 5 },
            { question: "Mead is an alcoholic beverage made by fermenting this sweet substance.", answer: "What is Honey?", difficulty: 3 },
            { question: "What does the 'VSOP' stand for on a Cognac bottle?", answer: "What is Very Superior Old Pale?", difficulty: 5 },
            { question: "Rum is made from...", answer: "What is Sugarcane/Molasses?", difficulty: 2 },
            { question: "Vodka basically means this in Russian.", answer: "What is Little Water?", difficulty: 4 },
            { question: "Sake is made from...", answer: "What is Rice?", difficulty: 1 },
            { question: "Bourbon must be made in this country.", answer: "What is The United States?", difficulty: 2 },
            { question: "Scotch must be made in this country.", answer: "What is Scotland?", difficulty: 1 },
            { question: "Sparkling wine must come from this French region to bear the name.", answer: "What is Champagne?", difficulty: 3 },
            { question: "The worm in the bottom of a bottle is actually found in...", answer: "What is Mezcal?", difficulty: 3 },
            { question: "Absinthe was banned for causing...", answer: "What is Hallucinations?", difficulty: 2 },
            { question: "Brandy is made from...", answer: "What is Grapes/Fruit?", difficulty: 2 },
            { question: "Cider is made from...", answer: "What is Apples?", difficulty: 1 },
            { question: "Soju is a popular spirit in...", answer: "What is South Korea?", difficulty: 3 },
            { question: "Baileys is an Irish...?", answer: "What is Cream Liqueur?", difficulty: 2 },
            { question: "Jägermeister contains this many herbs and spices.", answer: "What is 56?", difficulty: 5 },
            { question: "Kahlúa is a liqueur flavored with...", answer: "What is Coffee?", difficulty: 1 },
            { question: "Sambuca is flavored with...", answer: "What is Anise?", difficulty: 4 }
        ],
        "Famous Bars": [
            { question: "The bar where everybody knows your name.", answer: "What is Cheers?", difficulty: 1 },
            { question: "Quant's favorite cantina in Star Wars.", answer: "What is Mos Eisley Cantina?", difficulty: 2 },
            { question: "The pub in Shaun of the Dead.", answer: "What is The Winchester?", difficulty: 3 },
            { question: "The iconic Irish pub in 'It's Always Sunny in Philadelphia'.", answer: "What is Paddy's Pub?", difficulty: 2 },
            { question: "The bar in the Shining.", answer: "What is The Gold Room?", difficulty: 4 },
            { question: "The bar in How I Met Your Mother.", answer: "What is MacLaren's Pub?", difficulty: 3 },
            { question: "The bar in Friends (coffee shop, but iconic).", answer: "What is Central Perk?", difficulty: 1 },
            { question: "The bar in The Simpsons.", answer: "What is Moe's Tavern?", difficulty: 1 },
            { question: "The bar in Family Guy.", answer: "What is The Drunken Clam?", difficulty: 2 },
            { question: "The bar in Casablanca.", answer: "What is Rick's Café Américain?", difficulty: 5 },
            { question: "The rowdy New York bar featured in a 2000 film.", answer: "What is Coyote Ugly?", difficulty: 3 },
            { question: "The fictional bar in Harry Potter.", answer: "What is The Three Broomsticks?", difficulty: 2 },
            { question: "The bar in New Girl.", answer: "What is The Griffin?", difficulty: 4 },
            { question: "The bar in Grey's Anatomy.", answer: "What is Joe's Bar?", difficulty: 3 },
            { question: "The bar in The Sopranos.", answer: "What is Bada Bing!", difficulty: 3 },
            { question: "The bar in True Blood.", answer: "What is Fangtasia?", difficulty: 3 },
            { question: "The bar in Twin Peaks.", answer: "What is The Roadhouse?", difficulty: 4 },
            { question: "The bar in Goodfellas.", answer: "What is The Bamboo Lounge?", difficulty: 5 },
            { question: "The club in Scarface.", answer: "What is The Babylon Club?", difficulty: 5 },
            { question: "The bar in Indiana Jones.", answer: "What is Club Obi Wan?", difficulty: 5 }
        ],
        "Barroom Physics": [
            { question: "The force that keeps foam at the top of a beer.", answer: "What is Buoyancy?", difficulty: 2 },
            { question: "Why a Guinness bubble sinks (circulation patterns).", answer: "What is Drag?", difficulty: 4 },
            { question: "The effect that causes wine legs (tears).", answer: "What is The Marangoni Effect?", difficulty: 5 },
            { question: "Condensation forms on the outside of a cold glass because of this.", answer: "What is Dew Point?", difficulty: 3 },
            { question: "The density of alcohol relative to water (less or more).", answer: "What is Less?", difficulty: 2 },
            { question: "The shape of a liquid droplet is due to...", answer: "What is Surface Tension?", difficulty: 2 },
            { question: "Why ice floats in a drink.", answer: "What is Density (Ice is less dense)?", difficulty: 1 },
            { question: "The phenomenon where a sound wave matches the natural frequency of an object (like blowing across a bottle).", answer: "What is Resonance?", difficulty: 3 },
            { question: "The Coanda effect explains why liquid...?", answer: "What is Clings to the curved surface of a glass?", difficulty: 5 },
            { question: "The freezing point of alcohol is...?", answer: "What is Lower than water?", difficulty: 1 },
            { question: "Sublimation is when a solid turns directly into...", answer: "What is Gas?", difficulty: 2 },
            { question: "The Leidenfrost effect can be seen when liquid hits...", answer: "What is A hot surface?", difficulty: 4 },
            { question: "The study of fluids in motion.", answer: "What is Fluid Dynamics?", difficulty: 2 },
            { question: "Tiny imperfections in a glass where gas bubbles form.", answer: "What are Nucleation Sites?", difficulty: 4 },
            { question: "The scientific principle that pushes liquid up a straw when you suck on it.", answer: "What is Atmospheric Pressure?", difficulty: 2 },
            { question: "The meniscus of water in a glass curves...", answer: "What is Up?", difficulty: 3 },
            { question: "The meniscus of mercury in a glass curves...", answer: "What is Down?", difficulty: 3 },
            { question: "The speed of sound travels faster in liquids than in...", answer: "What is Gas?", difficulty: 2 },
            { question: "Refraction makes a straw look...", answer: "What is Bent?", difficulty: 1 },
            { question: "Viscosity is the measure of a fluid's...", answer: "What is Resistance to flow?", difficulty: 3 }
        ]
        ,
        "World Capitals": [
            { question: "Capital of France.", answer: "What is Paris?", difficulty: 1 },
            { question: "Capital of Japan.", answer: "What is Tokyo?", difficulty: 1 },
            { question: "Capital of Australia.", answer: "What is Canberra?", difficulty: 3 },
            { question: "Capital of Canada.", answer: "What is Ottawa?", difficulty: 2 },
            { question: "Capital of Brazil.", answer: "What is Brasília?", difficulty: 3 },
            { question: "Capital of Thailand.", answer: "What is Bangkok?", difficulty: 2 },
            { question: "Capital of Egypt.", answer: "What is Cairo?", difficulty: 2 },
            { question: "Capital of Turkey.", answer: "What is Ankara?", difficulty: 4 },
            { question: "Capital of Argentina.", answer: "What is Buenos Aires?", difficulty: 2 },
            { question: "Capital of Iceland.", answer: "What is Reykjavik?", difficulty: 4 },
            { question: "Capital of South Korea.", answer: "What is Seoul?", difficulty: 2 },
            { question: "Capital of Kenya.", answer: "What is Nairobi?", difficulty: 3 },
            { question: "Capital of Switzerland.", answer: "What is Bern?", difficulty: 4 },
            { question: "Capital of Peru.", answer: "What is Lima?", difficulty: 3 },
            { question: "Capital of Vietnam.", answer: "What is Hanoi?", difficulty: 3 },
            { question: "Capital of New Zealand.", answer: "What is Wellington?", difficulty: 3 },
            { question: "Capital of Morocco.", answer: "What is Rabat?", difficulty: 4 },
            { question: "Capital of Kazakhstan.", answer: "What is Astana?", difficulty: 5 },
            { question: "Capital of Mongolia.", answer: "What is Ulaanbaatar?", difficulty: 5 },
            { question: "Capital of Bhutan.", answer: "What is Thimphu?", difficulty: 5 }
        ],
        "Rivers & Lakes": [
            { question: "The longest river in the world.", answer: "What is The Nile (or Amazon)?", difficulty: 1 },
            { question: "The largest lake by surface area.", answer: "What is The Caspian Sea?", difficulty: 3 },
            { question: "The river that flows through London.", answer: "What is The Thames?", difficulty: 1 },
            { question: "The river that formed the Grand Canyon.", answer: "What is The Colorado River?", difficulty: 2 },
            { question: "The longest river in the United States.", answer: "What is The Missouri River?", difficulty: 4 },
            { question: "The deepest lake in the world.", answer: "What is Lake Baikal?", difficulty: 5 },
            { question: "The river that flows through Egypt.", answer: "What is The Nile?", difficulty: 1 },
            { question: "The river bordering Mexico and the US.", answer: "What is The Rio Grande?", difficulty: 2 },
            { question: "The Great Lake entirely within the US.", answer: "What is Lake Michigan?", difficulty: 3 },
            { question: "This river runs through Paris.", answer: "What is The Seine?", difficulty: 2 },
            { question: "The river known as 'Old Man River'.", answer: "What is The Mississippi?", difficulty: 2 },
            { question: "The longest river in Asia.", answer: "What is The Yangtze?", difficulty: 4 },
            { question: "The river that the Hoover Dam dams.", answer: "What is The Colorado River?", difficulty: 3 },
            { question: "The Scottish body of water famous for a mythical creature.", answer: "What is Loch Ness?", difficulty: 1 },
            { question: "The river flowing through Rome.", answer: "What is The Tiber?", difficulty: 4 },
            { question: "The Amazon river is primarily in this country.", answer: "What is Brazil?", difficulty: 1 },
            { question: "The river associated with Mark Twain.", answer: "What is The Mississippi?", difficulty: 2 },
            { question: "The waterfall on the border of US and Canada.", answer: "What is Niagara Falls?", difficulty: 1 },
            { question: "The river famously crossed by Caesar.", answer: "What is The Rubicon?", difficulty: 5 },
            { question: "The river that flows into the Dead Sea.", answer: "What is The Jordan River?", difficulty: 5 }
        ],
        "Mountains": [
            { question: "The highest peak in the world.", answer: "What is Mount Everest?", difficulty: 1 },
            { question: "The mountain range in South America.", answer: "What are The Andes?", difficulty: 2 },
            { question: "The highest peak in North America.", answer: "What is Denali (or Mt. McKinley)?", difficulty: 3 },
            { question: "The mountain range separating Europe and Asia.", answer: "What are The Urals?", difficulty: 4 },
            { question: "The highest mountain in Japan.", answer: "What is Mount Fuji?", difficulty: 1 },
            { question: "The mountain range stretching across Italy.", answer: "What are The Apennines?", difficulty: 5 },
            { question: "The highest peak in Africa.", answer: "What is Mount Kilimanjaro?", difficulty: 2 },
            { question: "The mountain range in the US including the Smokies.", answer: "What are The Appalachians?", difficulty: 2 },
            { question: "The mountain range in the western US.", answer: "What are The Rockies?", difficulty: 1 },
            { question: "The volcano that destroyed Pompeii.", answer: "What is Mount Vesuvius?", difficulty: 2 },
            { question: "The mountain range hosting the Matterhorn.", answer: "What are The Alps?", difficulty: 2 },
            { question: "The second highest mountain in the world.", answer: "What is K2?", difficulty: 3 },
            { question: "The mountain carved with presidents' faces.", answer: "What is Mount Rushmore?", difficulty: 1 },
            { question: "The highest mountain in the Alps.", answer: "What is Mont Blanc?", difficulty: 4 },
            { question: "The mythical home of the Greek Gods.", answer: "What is Mount Olympus?", difficulty: 1 },
            { question: "The volcano in Washington state that erupted in 1980.", answer: "What is Mount St. Helens?", difficulty: 2 },
            { question: "The mountain range in Morocco.", answer: "What are The Atlas Mountains?", difficulty: 5 },
            { question: "The highest mountain in Antarctica.", answer: "What is Vinson Massif?", difficulty: 5 },
            { question: "The mountain range bordering France and Spain.", answer: "What are The Pyrenees?", difficulty: 4 },
            { question: "The holy mountain in Tibet (never climbed).", answer: "What is Kailash?", difficulty: 5 }
        ],
        "Islands": [
            { question: "The largest island in the world.", answer: "What is Greenland?", difficulty: 1 },
            { question: "The island nation known for lemurs.", answer: "What is Madagascar?", difficulty: 2 },
            { question: "The island state of the US.", answer: "What is Hawaii?", difficulty: 1 },
            { question: "The island divided between Indonesia, Malaysia, and Brunei.", answer: "What is Borneo?", difficulty: 4 },
            { question: "The island south of India.", answer: "What is Sri Lanka?", difficulty: 2 },
            { question: "The island where Napoleon was born.", answer: "What is Corsica?", difficulty: 4 },
            { question: "The island famous for its Moai statues.", answer: "What is Easter Island?", difficulty: 3 },
            { question: "The island group including Tenerife.", answer: "What are The Canary Islands?", difficulty: 3 },
            { question: "The largest island in the Caribbean.", answer: "What is Cuba?", difficulty: 2 },
            { question: "The island nation south of Australia.", answer: "What is Tasmania?", difficulty: 3 },
            { question: "The island where King Kong lives.", answer: "What is Skull Island?", difficulty: 1 },
            { question: "The island used as a prison in San Francisco Bay.", answer: "What is Alcatraz?", difficulty: 1 },
            { question: "The island of the gods in Indonesia.", answer: "What is Bali?", difficulty: 2 },
            { question: "The island associated with Darwin's finches.", answer: "What are The Galápagos Islands?", difficulty: 2 },
            { question: "The island comprising England, Scotland, and Wales.", answer: "What is Great Britain?", difficulty: 2 },
            { question: "The island nation divided into North and South.", answer: "What is Ireland (technically divided)?", difficulty: 3 },
            { question: "The island in New York Harbor with the Statue of Liberty.", answer: "What is Liberty Island?", difficulty: 2 },
            { question: "The island disputed by China and recognized by few nations.", answer: "What is Taiwan?", difficulty: 4 },
            { question: "The island home of the Minotaur.", answer: "What is Crete?", difficulty: 4 },
            { question: "The island formerly known as Ceylon.", answer: "What is Sri Lanka?", difficulty: 4 }
        ],
        "Landmarks": [
            { question: "The iron tower in Paris.", answer: "What is The Eiffel Tower?", difficulty: 1 },
            { question: "The ancient amphitheater in Rome.", answer: "What is The Colosseum?", difficulty: 1 },
            { question: "The big clock tower in London.", answer: "What is Elizabeth Tower (Big Ben)?", difficulty: 1 },
            { question: "The immense wall in China.", answer: "What is The Great Wall of China?", difficulty: 1 },
            { question: "The mausoleum in Agra, India.", answer: "What is The Taj Mahal?", difficulty: 2 },
            { question: "The ancient city in Jordan carved into rock.", answer: "What is Petra?", difficulty: 3 },
            { question: "The Inca citadel in Peru.", answer: "What is Machu Picchu?", difficulty: 2 },
            { question: "The statue overlooking Rio de Janeiro.", answer: "What is Christ the Redeemer?", difficulty: 2 },
            { question: "The prehistoric stone circle in England.", answer: "What is Stonehenge?", difficulty: 2 },
            { question: "The opera house with sail-like roofs.", answer: "What is The Sydney Opera House?", difficulty: 2 },
            { question: "The skyscraper in Dubai (tallest in world).", answer: "What is The Burj Khalifa?", difficulty: 3 },
            { question: "The red bridge in San Francisco.", answer: "What is The Golden Gate Bridge?", difficulty: 1 },
            { question: "The ancient pyramids near Cairo.", answer: "What are The Great Pyramids of Giza?", difficulty: 1 },
            { question: "The statue in New York Harbor.", answer: "What is The Statue of Liberty?", difficulty: 1 },
            { question: "The leaning tower in Italy.", answer: "What is The Leaning Tower of Pisa?", difficulty: 1 },
            { question: "The temple complex in Cambodia.", answer: "What is Angkor Wat?", difficulty: 4 },
            { question: "The church in Barcelona still under construction.", answer: "What is La Sagrada Família?", difficulty: 4 },
            { question: "The ancient citadel in Athens.", answer: "What is The Acropolis?", difficulty: 3 },
            { question: "The palace of the French kings near Paris.", answer: "What is Versailles?", difficulty: 3 },
            { question: "The canyon in Arizona.", answer: "What is The Grand Canyon?", difficulty: 1 }
        ],
        "Olympics": [
            { question: "The city that hosted the 2024 Summer Olympics.", answer: "What is Paris?", difficulty: 1 },
            { question: "The number of rings in the Olympic flag.", answer: "What is Five?", difficulty: 1 },
            { question: "The fastest man in history (100m/200m).", answer: "Who is Usain Bolt?", difficulty: 1 },
            { question: "The swimmer with the most Olympic medals.", answer: "Who is Michael Phelps?", difficulty: 1 },
            { question: "The metal used for second-place medals.", answer: "What is Silver?", difficulty: 1 },
            { question: "The year the first modern Olympics were held.", answer: "What is 1896?", difficulty: 4 },
            { question: "The country that originated the Olympics.", answer: "What is Greece?", difficulty: 1 },
            { question: "The gymnast known as the G.O.A.T.", answer: "Who is Simone Biles?", difficulty: 2 },
            { question: "The sport introduced in 2024 involving dancing.", answer: "What is Breakdancing (Breaking)?", difficulty: 3 },
            { question: "The city hosting the 2028 Summer Olympics.", answer: "What is Los Angeles?", difficulty: 2 },
            { question: "The winter sport combining cross-country skiing and shooting.", answer: "What is Biathlon?", difficulty: 3 },
            { question: "The Jamaican bobsled team debuted in this year.", answer: "What is 1988?", difficulty: 3 },
            { question: "The Miracle on Ice happened in this sport.", answer: "What is Ice Hockey?", difficulty: 2 },
            { question: "The only country to have hosted the Summer Olympics 4 times (by 2028).", answer: "What is The United States?", difficulty: 3 },
            { question: "The torch relay ends at this location.", answer: "What is The Olympic Cauldron?", difficulty: 2 },
            { question: "The number of gold medals Mark Spitz won in 1972.", answer: "What is Seven?", difficulty: 4 },
            { question: "The first woman to score a perfect 10 in gymnastics.", answer: "Who is Nadia Comăneci?", difficulty: 4 },
            { question: "The distance of a marathon.", answer: "What is 26.2 miles?", difficulty: 2 },
            { question: "The sport played with a shuttlecock.", answer: "What is Badminton?", difficulty: 2 },
            { question: "The location of the 2016 Summer Olympics.", answer: "What is Rio de Janeiro?", difficulty: 3 }
        ],
        "NFL Legends": [
            { question: "The quarterback with the most Super Bowl rings.", answer: "Who is Tom Brady?", difficulty: 1 },
            { question: "The only team to have a perfect season (1972).", answer: "Who are The Miami Dolphins?", difficulty: 3 },
            { question: "The MVP of Super Bowl LVII (Chiefs).", answer: "Who is Patrick Mahomes?", difficulty: 2 },
            { question: "The wide receiver considered the G.O.A.T.", answer: "Who is Jerry Rice?", difficulty: 2 },
            { question: "The defense nicknamed 'The Steel Curtain'.", answer: "Who are The Pittsburgh Steelers?", difficulty: 3 },
            { question: "The coach of the New England Patriots dynasty.", answer: "Who is Bill Belichick?", difficulty: 2 },
            { question: "The running back nicknamed 'Sweetness'.", answer: "Who is Walter Payton?", difficulty: 4 },
            { question: "The city the Colts moved from.", answer: "What is Baltimore?", difficulty: 4 },
            { question: "The name of the Super Bowl trophy.", answer: "What is The Lombardi Trophy?", difficulty: 2 },
            { question: "The quarterback known as 'The Sheriff'.", answer: "Who is Peyton Manning?", difficulty: 2 },
            { question: "The team with the most Super Bowl wins.", answer: "Who are The Patriots/Steelers?", difficulty: 3 },
            { question: "The linebacker Ray Lewis played for.", answer: "Who are The Baltimore Ravens?", difficulty: 2 },
            { question: "The quarterback who guaranteed a win in Super Bowl III.", answer: "Who is Joe Namath?", difficulty: 5 },
            { question: "The 'Refrigerator' played for this team.", answer: "Who are The Chicago Bears?", difficulty: 3 },
            { question: "The quarterback who caught his own pass.", answer: "Who is Brett Favre?", difficulty: 5 },
            { question: "The 'Immaculate Reception' involved this team.", answer: "Who are The Pittsburgh Steelers?", difficulty: 4 },
            { question: "The team that went 0-16 in 2008.", answer: "Who are The Detroit Lions?", difficulty: 4 },
            { question: "The oldest player to play in the NFL.", answer: "Who is George Blanda?", difficulty: 5 },
            { question: "The brothers who faced off in the Super Bowl (coaches).", answer: "Who are Jim and John Harbaugh?", difficulty: 3 },
            { question: "The defensive player nicknamed 'Prime Time'.", answer: "Who is Deion Sanders?", difficulty: 2 }
        ],
        "NBA Hoops": [
            { question: "The player with the most NBA championships (11).", answer: "Who is Bill Russell?", difficulty: 1 },
            { question: "The player nicknamed 'Air Jordan'.", answer: "Who is Michael Jordan?", difficulty: 1 },
            { question: "The team that drafted Kobe Bryant.", answer: "Who are The Charlotte Hornets?", difficulty: 5 },
            { question: "The all-time leading scorer in NBA history (as of 2024).", answer: "Who is LeBron James?", difficulty: 2 },
            { question: "The team with the most NBA championships.", answer: "Who are The Boston Celtics?", difficulty: 2 },
            { question: "The player who scored 100 points in a single game.", answer: "Who is Wilt Chamberlain?", difficulty: 3 },
            { question: "The player nicknamed 'The greek Freak'.", answer: "Who is Giannis Antetokounmpo?", difficulty: 2 },
            { question: "The team 'Showtime' refers to.", answer: "Who are The Los Angeles Lakers?", difficulty: 3 },
            { question: "The shortest player in NBA history.", answer: "Who is Muggsy Bogues?", difficulty: 4 },
            { question: "The player nicknamed 'The Answer'.", answer: "Who is Allen Iverson?", difficulty: 3 },
            { question: "The number Michael Jordan wore (mostly).", answer: "What is 23?", difficulty: 1 },
            { question: "The Splash Brothers play for this team.", answer: "Who are The Golden State Warriors?", difficulty: 2 },
            { question: "The player nicknamed 'Shaq'.", answer: "Who is Shaquille O'Neal?", difficulty: 1 },
            { question: "The Dream Team played in this year's Olympics.", answer: "What is 1992?", difficulty: 3 },
            { question: "The player nicknamed 'Magic'.", answer: "Who is Earvin Johnson?", difficulty: 1 },
            { question: "The year the NBA was founded.", answer: "What is 1946?", difficulty: 5 },
            { question: "The player nicknamed 'The Klaw'.", answer: "Who is Kawhi Leonard?", difficulty: 4 },
            { question: "The first overall pick in the 2003 NBA draft.", answer: "Who is LeBron James?", difficulty: 2 },
            { question: "The team Larry Bird played for.", answer: "Who are The Boston Celtics?", difficulty: 2 },
            { question: "The European player nicknamed 'The Joker'.", answer: "Who is Nikola Jokic?", difficulty: 3 }
        ],
        "World Cup Soccer": [
            { question: "The country with the most World Cup titles.", answer: "What is Brazil?", difficulty: 1 },
            { question: "The player nicknamed 'Pele'.", answer: "Who is Edson Arantes do Nascimento?", difficulty: 2 },
            { question: "The country that hosted the 2022 World Cup.", answer: "What is Qatar?", difficulty: 2 },
            { question: "The winner of the 2022 World Cup.", answer: "What is Argentina?", difficulty: 2 },
            { question: "The player who scored the 'Hand of God' goal.", answer: "Who is Diego Maradona?", difficulty: 3 },
            { question: "The country that hosted the 2014 World Cup.", answer: "What is Brazil?", difficulty: 3 },
            { question: "The total number of players on the field per team.", answer: "What is 11?", difficulty: 1 },
            { question: "The only goalkeeper to win the Golden Ball (MVP).", answer: "Who is Oliver Kahn?", difficulty: 5 },
            { question: "The player nicknamed 'CR7'.", answer: "Who is Cristiano Ronaldo?", difficulty: 1 },
            { question: "The country that won the 2018 World Cup.", answer: "What is France?", difficulty: 3 },
            { question: "The player nicknamed 'The Flea' (La Pulga).", answer: "Who is Lionel Messi?", difficulty: 2 },
            { question: "The country that hosted the 1994 World Cup.", answer: "What is The United States?", difficulty: 4 },
            { question: "The trophy currently awarded is called...", answer: "What is The FIFA World Cup Trophy?", difficulty: 1 },
            { question: "The country that won the first World Cup in 1930.", answer: "What is Uruguay?", difficulty: 5 },
            { question: "The player who headbutted Materazzi in the 2006 final.", answer: "Who is Zinedine Zidane?", difficulty: 3 },
            { question: "The name of the ball used in the 2010 World Cup (noisy).", answer: "What is The Jabulani?", difficulty: 4 },
            { question: "The maximum duration of a match before stoppage time.", answer: "What is 90 minutes?", difficulty: 1 },
            { question: "The country set to co-host the 2026 World Cup (one of three).", answer: "What is USA/Canada/Mexico?", difficulty: 2 },
            { question: "The player with the most goals in World Cup history.", answer: "Who is Miroslav Klose?", difficulty: 5 },
            { question: "The card shown for a warning.", answer: "What is Yellow?", difficulty: 1 }
        ],
        "Classic Novels": [
            { question: "He wrote 'Moby Dick'.", answer: "Who is Herman Melville?", difficulty: 3 },
            { question: "The author of 'Pride and Prejudice'.", answer: "Who is Jane Austen?", difficulty: 1 },
            { question: "The Great Gatsby features this mysterious millionaire.", answer: "Who is Jay Gatsby?", difficulty: 1 },
            { question: "The novel set in a dystopian 1984.", answer: "What is 1984?", difficulty: 1 },
            { question: "The author of 'To Kill a Mockingbird'.", answer: "Who is Harper Lee?", difficulty: 2 },
            { question: "The main character in 'Catcher in the Rye'.", answer: "Who is Holden Caulfield?", difficulty: 2 },
            { question: "The author of 'The Adventures of Tom Sawyer'.", answer: "Who is Mark Twain?", difficulty: 1 },
            { question: "The novel beginning 'It was the best of times, it was the worst of times'.", answer: "What is A Tale of Two Cities?", difficulty: 3 },
            { question: "The author of 'Frankenstein'.", answer: "Who is Mary Shelley?", difficulty: 3 },
            { question: "The novel about a pig named Napoleon.", answer: "What is Animal Farm?", difficulty: 2 },
            { question: "The author of 'The Grapes of Wrath'.", answer: "Who is John Steinbeck?", difficulty: 4 },
            { question: "The novel featuring the character Atticus Finch.", answer: "What is To Kill a Mockingbird?", difficulty: 1 },
            { question: "The author of 'War and Peace'.", answer: "Who is Leo Tolstoy?", difficulty: 4 },
            { question: "The novel about a dystopian future where books are burned.", answer: "What is Fahrenheit 451?", difficulty: 3 },
            { question: "The author of 'Jane Eyre'.", answer: "Who is Charlotte Brontë?", difficulty: 4 },
            { question: "The captain of the Nautilus in '20,000 Leagues Under the Sea'.", answer: "Who is Captain Nemo?", difficulty: 3 },
            { question: "The author of 'Crime and Punishment'.", answer: "Who is Fyodor Dostoevsky?", difficulty: 5 },
            { question: "The novel featuring Big Brother.", answer: "What is 1984?", difficulty: 1 },
            { question: "The author of 'Brave New World'.", answer: "Who is Aldous Huxley?", difficulty: 5 },
            { question: "The novel set during the Jazz Age.", answer: "What is The Great Gatsby?", difficulty: 2 }
        ],
        "Shakespeare": [
            { question: "The play featuring Romeo and Juliet.", answer: "What is Romeo and Juliet?", difficulty: 1 },
            { question: "The Prince of Denmark.", answer: "Who is Hamlet?", difficulty: 1 },
            { question: "The play with the line 'To be or not to be'.", answer: "What is Hamlet?", difficulty: 1 },
            { question: "The Scottish Play.", answer: "What is Macbeth?", difficulty: 2 },
            { question: "The villain in Othello.", answer: "Who is Iago?", difficulty: 3 },
            { question: "The play featuring a donkey-headed Bottom.", answer: "What is A Midsummer Night's Dream?", difficulty: 3 },
            { question: "The merchant of Venice.", answer: "Who is Antonio (or Shylock)?", difficulty: 4 },
            { question: "The play featuring an aging monarch dividing his kingdom.", answer: "What is King Lear?", difficulty: 3 },
            { question: "The wife of Macbeth.", answer: "Who is Lady Macbeth?", difficulty: 2 },
            { question: "The play featuring Prospero and Puck.", answer: "What is The Tempest?", difficulty: 3 },
            { question: "The play where Caesar is assassinated.", answer: "What is Julius Caesar?", difficulty: 1 },
            { question: "The famous balcony scene is in...", answer: "What is Romeo and Juliet?", difficulty: 1 },
            { question: "The phrase 'Et tu, Brute?' is from...", answer: "What is Julius Caesar?", difficulty: 1 },
            { question: "The play featuring the character Falstaff.", answer: "What is Henry IV (or Merry Wives)?", difficulty: 4 },
            { question: "The shrew to be tamed.", answer: "Who is Katherina?", difficulty: 4 },
            { question: "The play featuring Rosalind and Orlando.", answer: "What is As You Like It?", difficulty: 5 },
            { question: "The play featuring Beatrice and Benedick.", answer: "What is Much Ado About Nothing?", difficulty: 5 },
            { question: "Shakespeare's wife.", answer: "Who is Anne Hathaway?", difficulty: 3 },
            { question: "The theater Shakespeare is associated with.", answer: "What is The Globe?", difficulty: 2 },
            { question: "The number of sonnets Shakespeare wrote (approx).", answer: "What is 154?", difficulty: 5 }
        ],
        "Biology": [
            { question: "The basic unit of life.", answer: "What is The Cell?", difficulty: 1 },
            { question: "The molecule containing genetic instructions.", answer: "What is DNA?", difficulty: 1 },
            { question: "The process plants use to make food.", answer: "What is Photosynthesis?", difficulty: 1 },
            { question: "The powerhouse of the cell.", answer: "What is Mitochondria?", difficulty: 1 },
            { question: "The largest organ in the human body.", answer: "What is Skin?", difficulty: 2 },
            { question: "The pump of the circulatory system.", answer: "What is The Heart?", difficulty: 1 },
            { question: "Animals that eat only plants.", answer: "What are Herbivores?", difficulty: 1 },
            { question: "The study of heredity.", answer: "What is Genetics?", difficulty: 2 },
            { question: "The scientist who proposed evolution by natural selection.", answer: "Who is Charles Darwin?", difficulty: 2 },
            { question: "The green pigment in plants.", answer: "What is Chlorophyll?", difficulty: 2 },
            { question: "The number of chromosomes in a human cell.", answer: "What is 46 (23 pairs)?", difficulty: 3 },
            { question: "The kingdom of mushrooms and molds.", answer: "What is Fungi?", difficulty: 2 },
            { question: "The process of cell division.", answer: "What is Mitosis?", difficulty: 3 },
            { question: "The hard outer covering of an insect.", answer: "What is Exoskeleton?", difficulty: 3 },
            { question: "The classification group below Kingdom.", answer: "What is Phylum?", difficulty: 4 },
            { question: "The voice box in humans.", answer: "What is The Larynx?", difficulty: 4 },
            { question: "The thigh bone (longest in body).", answer: "What is The Femur?", difficulty: 2 },
            { question: "The study of insects.", answer: "What is Entomology?", difficulty: 5 },
            { question: "The sugar found in milk.", answer: "What is Lactose?", difficulty: 3 },
            { question: "A biological catalyst.", answer: "What is An Enzyme?", difficulty: 4 }
        ],
        "Physics": [
            { question: "F = ma is Newton's ___ Law.", answer: "What is Second?", difficulty: 2 },
            { question: "The force that resists motion.", answer: "What is Friction?", difficulty: 1 },
            { question: "The unit of force.", answer: "What is The Newton?", difficulty: 3 },
            { question: "Energy of motion.", answer: "What is Kinetic Energy?", difficulty: 2 },
            { question: "The rate of change of velocity.", answer: "What is Acceleration?", difficulty: 2 },
            { question: "The speed of light (approx).", answer: "What is 300,000 km/s?", difficulty: 3 },
            { question: "The particle with a negative charge.", answer: "What is An Electron?", difficulty: 1 },
            { question: "The particle with a positive charge.", answer: "What is A Proton?", difficulty: 1 },
            { question: "The particle with no charge.", answer: "What is A Neutron?", difficulty: 1 },
            { question: "The force that holds the nucleus together.", answer: "What is The Strong Nuclear Force?", difficulty: 5 },
            { question: "E = mc^2 was proposed by...", answer: "Who is Einstein?", difficulty: 1 },
            { question: "The bending of light.", answer: "What is Refraction?", difficulty: 3 },
            { question: "The unit of electrical resistance.", answer: "What is The Ohm?", difficulty: 4 },
            { question: "The law of conservation of...", answer: "What is Energy?", difficulty: 1 },
            { question: "The device used to measure current.", answer: "What is An Ammeter?", difficulty: 4 },
            { question: "The upward force on a floating object.", answer: "What is Buoyancy?", difficulty: 2 },
            { question: "The theoretical temperature where molecular motion stops.", answer: "What is Absolute Zero?", difficulty: 3 },
            { question: "The unit of frequency.", answer: "What is Hertz?", difficulty: 2 },
            { question: "Sound cannot travel through...", answer: "What is A Vacuum?", difficulty: 2 },
            { question: "The first law of thermodynamics is about...", answer: "What is Conservation of Energy?", difficulty: 4 }
        ],
        "Horror Movies": [
            { question: "The killer in the 'Halloween' franchise.", answer: "Who is Michael Myers?", difficulty: 1 },
            { question: "The movie featuring a possessed girl named Regan.", answer: "What is The Exorcist?", difficulty: 2 },
            { question: "The villain in 'A Nightmare on Elm Street'.", answer: "Who is Freddy Krueger?", difficulty: 1 },
            { question: "The mask worn by the killer in 'Scream'.", answer: "What is Ghostface?", difficulty: 1 },
            { question: "The motel in 'Psycho'.", answer: "What is The Bates Motel?", difficulty: 2 },
            { question: "The movie with the line 'Here's Johnny!'.", answer: "What is The Shining?", difficulty: 2 },
            { question: "The killer in 'Friday the 13th'.", answer: "Who is Jason Voorhees?", difficulty: 1 },
            { question: "The director of 'Get Out'.", answer: "Who is Jordan Peele?", difficulty: 2 },
            { question: "The movie about a found footage witch hunt.", answer: "What is The Blair Witch Project?", difficulty: 3 },
            { question: "The clown in 'It'.", answer: "Who is Pennywise?", difficulty: 2 },
            { question: "The movie with the line 'They're here'.", answer: "What is Poltergeist?", difficulty: 3 },
            { question: "The zombie movie directed by George Romero.", answer: "What is Night of the Living Dead?", difficulty: 4 },
            { question: "The movie featuring a girl crawling out of a TV.", answer: "What is The Ring?", difficulty: 2 },
            { question: "The villain in 'The Texas Chain Saw Massacre'.", answer: "Who is Leatherface?", difficulty: 3 },
            { question: "The movie where silence is deadly.", answer: "What is A Quiet Place?", difficulty: 2 },
            { question: "The birds in 'The Birds' do this.", answer: "What is Attack people?", difficulty: 1 },
            { question: "The director of 'Psycho'.", answer: "Who is Alfred Hitchcock?", difficulty: 3 },
            { question: "The movie featuring the 'Red Room'.", answer: "What is The Shining?", difficulty: 5 },
            { question: "The year the original 'Halloween' was released.", answer: "What is 1978?", difficulty: 5 },
            { question: "The horror movie set on a spaceship.", answer: "What is Alien?", difficulty: 2 }
        ],
        "Disney Villains": [
            { question: "The sea witch in 'The Little Mermaid'.", answer: "Who is Ursula?", difficulty: 1 },
            { question: "The lion who killed Mufasa.", answer: "Who is Scar?", difficulty: 1 },
            { question: "The sorcerer in 'Aladdin'.", answer: "Who is Jafar?", difficulty: 1 },
            { question: "The hunter in 'Beauty and the Beast'.", answer: "Who is Gaston?", difficulty: 1 },
            { question: "The fairy who cursed Sleeping Beauty.", answer: "Who is Maleficent?", difficulty: 2 },
            { question: "The villain who wants to make a coat out of puppies.", answer: "Who is Cruella de Vil?", difficulty: 1 },
            { question: "The god of the underworld in 'Hercules'.", answer: "Who is Hades?", difficulty: 2 },
            { question: "The queen in 'Snow White'.", answer: "Who is The Evil Queen?", difficulty: 2 },
            { question: "The pirate captain in 'Peter Pan'.", answer: "Who is Captain Hook?", difficulty: 1 },
            { question: "The tiger in 'The Jungle Book'.", answer: "Who is Shere Khan?", difficulty: 3 },
            { question: "The villain in 'The Princess and the Frog'.", answer: "Who is Dr. Facilier?", difficulty: 3 },
            { question: "The mother in 'Tangled'.", answer: "Who is Mother Gothel?", difficulty: 2 },
            { question: "The emperor in 'The Emperor's New Groove' (initially).", answer: "Who is Kuzco (or Yzma)?", difficulty: 3 },
            { question: "The villain in 'Mulan'.", answer: "Who is Shan Yu?", difficulty: 4 },
            { question: "The villain in 'Pocahontas'.", answer: "Who is Governor Ratcliffe?", difficulty: 4 },
            { question: "The bear in 'Toy Story 3'.", answer: "Who is Lotso?", difficulty: 3 },
            { question: "The villain in 'The Incredibles'.", answer: "Who is Syndrome?", difficulty: 2 },
            { question: "The villain in 'Wreck-It Ralph'.", answer: "Who is King Candy / Turbo?", difficulty: 4 },
            { question: "The villain in 'Frozen' (twist).", answer: "Who is Hans?", difficulty: 2 },
            { question: "The villain in '101 Dalmatians'.", answer: "Who is Cruella de Vil?", difficulty: 1 }
        ]
    }
};